- .gitignore
- Resources/Common/Common.robot
- Resources/Common/Common_Yves.robot
- Resources/Pages/Yves/Yves_Quote_Request_page.robot
- Resources/Steps/Header_steps.robot
- Resources/Steps/Request_for_Quote_steps.robot
- Resources/Steps/Shopping_Carts_steps.robot
- Resources/Steps/Users_steps.robot
- Tests/User_Journeys/B2B_Demo_Script.robot
- Fixed tests
- Fixed locators
- Fixed Zed delete agent method
**Note:** Request_for_Quote test is commended because he can be runned only one time with his test data. So make sure you want to run this test.
> Refactor tests

- Resources/Common/Common.robot
- Resources/Common/Common_Yves.robot
- Resources/Pages/Yves/Yves_Quote_Request_page.robot
- Resources/Steps/Request_for_Quote_steps.robot
- Resources/Steps/Shopping_Carts_steps.robot
- Tests/E2E/B2B_E2E.robot
> make RfQ test 'independent'

- Resources/Common/Common.robot
- Resources/Common/Common_Yves.robot
- Resources/Common/Common_Zed.robot
- Resources/Pages/Yves/Yves_Catalog_page.robot
- Resources/Pages/Yves/Yves_Create_Return_page.robot
- Resources/Pages/Yves/Yves_Product_Details_Page.robot
- Resources/Pages/Yves/Yves_Return_Details_page.robot
- Resources/Pages/Yves/Yves_Return_Slip_page.robot
- Resources/Pages/Yves/Yves_Shopping_Lists_page.robot
- Resources/Pages/Zed/Zed_Create_Return_page.robot
- Resources/Pages/Zed/Zed_Delete_User_Confirmation_page.robot
- Resources/Pages/Zed/Zed_Edit_Product_page.robot
- Resources/Pages/Zed/Zed_Order_Details_page.robot
- Resources/Pages/Zed/Zed_Return_Details_page.robot
- Resources/Steps/Header_steps.robot
- Resources/Steps/Order_History_steps.robot
- Resources/Steps/Orders_Management_steps.robot
- Resources/Steps/PDP_steps.robot
- Resources/Steps/Products_steps.robot
- Resources/Steps/Request_for_Quote_steps.robot
- Resources/Steps/Shopping_Carts_steps.robot
- Resources/Steps/Shopping_Lists_steps.robot
- Resources/Steps/Zed_Users_steps.robot
- Tests/E2E/B2B_E2E.robot
- Tests/Features/Agent_Assist.robot
> return management tests

- Resources/Common/Common_Yves.robot
- Resources/Pages/Yves/Yves_Shopping_Lists_page.robot
- Resources/Steps/Shopping_Lists_steps.robot
Ticket https://spryker.atlassian.net/browse/DQIB-2468
> Dqib 2468 extend yves go to shopping list page method

- Resources/Environments/environments_ci_b2b.json
Environment JSON data for b2b CI
> Environment JSON data for b2b CI

- Tests/E2E/B2B_E2E.robot
Passwords for agent creation were changed from "change123" to "change123${random}" as old passwords are not acceptable due to security reasons
> changed password for agent creation

- resources/common/common_yves.robot
- resources/environments/environments_b2b.json
- resources/environments/environments_b2c.json
- resources/pages/yves/yves_customer_account_page.robot
- resources/pages/yves/yves_product_details_page.robot
- resources/pages/yves/yves_shopping_cart_page.robot
- resources/steps/customer_account_steps.robot
- tests/smoke/smoke_b2b.robot
- tests/smoke/smoke_b2c.robot
Add common tests missing in b2b and b2b suites
> Enhance b2c and b2b test sets

- .gitignore
- resources/common/common.robot
- resources/common/common_yves.robot
- resources/libraries/common.py
> Fixed incorrect typecasting

- README.md
- resources/Environments/environments_api_suite.json
- resources/common/common.robot
- resources/common/common_api.robot
- tests/api/examples.robot
- tests/api/suite-nonsplit.robot
* enabler for API testing
** added https://marketsquare.github.io/robotframework-requests/doc/RequestsLibrary.html library for API testing 
** created custom keywords to simplify tests creation
> enabler for API testing

- resources/environments/environments_b2b.json
- tests/api/b2b/glue/concrete_products_endpoints/concrete_alternative_products/negative.robot
- tests/api/b2b/glue/concrete_products_endpoints/concrete_alternative_products/positive.robot
added concrete-alternative-products for b2b
> added concrete-alternative-products for b2b

- tests/api/b2b/glue/availability_endpoints/negative.robot
- tests/api/b2b/glue/availability_endpoints/positive.robot
- Created positive and negative tests for /availability-notifications endpoint
- API schema doesn't contain 'body request' for POST
- Found 1 issue regarding POST request with invalid SKU (negative case), now the response has #500 error code, should be discussed with @Jeremy Fourna
> added availability-notifications for b2b

- resources/environments/environments_api_b2c.json
- tests/api/b2c/glue/access_token_endpoints/access_tokens/negative.robot
- tests/api/b2c/glue/access_token_endpoints/access_tokens/positive.robot
- tests/api/b2c/glue/access_token_endpoints/refresh_tokens/negative.robot
- tests/api/b2c/glue/access_token_endpoints/refresh_tokens/positive.robot
- tests/api/b2c/glue/customer_endpoints/addresses/negative.robot
- tests/api/b2c/glue/customer_endpoints/addresses/positive.robot
Add b2c test Infrastructure,  access_token_endpoints and customer_endpoints
> b2c test Infrastructure, access_token_endpoints and customer_endpoints

- resources/environments/environments_api_b2c.json
- tests/api/b2b/glue/concrete_products_endpoints/concrete_alternative_products/negative.robot
- tests/api/b2c/glue/abstract_product_endpoints/abstract_alternative_products/positive.robot
- tests/api/b2c/glue/abstract_product_endpoints/abstract_product_availabilities/negative.robot
- tests/api/b2c/glue/abstract_product_endpoints/abstract_product_image_sets/negative.robot
- tests/api/b2c/glue/abstract_product_endpoints/abstract_product_prices/negative.robot
- tests/api/b2c/glue/abstract_product_endpoints/abstract_products/negative.robot
- tests/api/b2c/glue/concrete_products_endpoints/concrete_alternative_products/negative.robot
- tests/api/b2c/glue/concrete_products_endpoints/concrete_alternative_products/positive.robot
- tests/api/b2c/glue/concrete_products_endpoints/concrete_product_availabilities/negative.robot
- tests/api/b2c/glue/concrete_products_endpoints/concrete_product_availabilities/positive.robot
- tests/api/b2c/glue/concrete_products_endpoints/concrete_product_image_sets/negative.robot
- tests/api/b2c/glue/concrete_products_endpoints/concrete_product_image_sets/positive.robot
- tests/api/b2c/glue/concrete_products_endpoints/concrete_product_prices/negative.robot
- tests/api/b2c/glue/concrete_products_endpoints/concrete_product_prices/positive.robot
- tests/api/b2c/glue/concrete_products_endpoints/concrete_products/negative.robot
- tests/api/b2c/glue/concrete_products_endpoints/concrete_products/positive.robot
CC-16204, CC-16209, CC-16214, CC-16219, CC-16224 finish concrete_product_endpoints + minor fixes (sku variables) to the abstract_product_endpoints
> B2c concrete products endpoints

- tests/api/b2b/glue/utility_endpoints/negative.robot
- tests/api/b2b/glue/utility_endpoints/positive.robot
- created the bug https://spryker.atlassian.net/browse/CC-16492
- added health-check endpoint
NOTE: to run positive tests need to enable services
> added health-check for b2b

- resources/environments/environments_api_b2b.json
- tests/api/b2b/glue/category_endpoints/category_nodes/negative.robot
- tests/api/b2b/glue/category_endpoints/category_nodes/positive.robot
Create B2B Category nodes Positive and Negative tests
[Sub-Task On Jira](https://spryker.atlassian.net/browse/CC-16150)
> B2b b2b category nodes

- resources/environments/environments_api_b2b.json
- tests/api/b2b/glue/general_product_endpoints/related_products/negative.robot
- tests/api/b2b/glue/general_product_endpoints/related_products/positive.robot
New API tests have been added for related products endpoint in b2b env
TBD
none
> Tests created for related products endpoint (b2b)

- resources/environments/environments_api_b2b.json
- tests/api/b2b/glue/customer_endpoints/customer_password/negative.robot
- tests/api/b2b/glue/customer_endpoints/customer_password/positive.robot
- tests/api/b2b/glue/customer_endpoints/customer_restore_password/negative.robot
- tests/api/b2b/glue/customer_endpoints/customer_restore_password/positive.robot
- tests/api/b2b/glue/customer_endpoints/customers/negative.robot
- tests/api/b2b/glue/customer_endpoints/customers/positive.robot
tests for
customers/ customer_restore_password/ customer_password/
TBD
> b2b customers and customer_restore_password and customer_password

- resources/common/common_api.robot
- resources/environments/environments_api_b2b.json
- tests/api/b2b/glue/cart_endpoints/cart-permssion-groups/negitive.robot
- tests/api/b2b/glue/cart_endpoints/cart-permssion-groups/positive.robot
Create tests for cart-permission-groups
this test `Get_cart_permission_groups_by_cart_id` is included with following the scheme in swagger
but it's introduced a bug https://spryker.atlassian.net/browse/CC-16527
after bug is resolved I will uncomment it
> create test for cart-permission-groups

- resources/common/common_api.robot
- resources/environments/environments_api_b2b.json
- tests/api/b2b/glue/general_product_endpoints/upselling_products/negative.robot
- tests/api/b2b/glue/general_product_endpoints/upselling_products/positive.robot
b2b up-selling products endpoint tests + dummy value update
Note: 'test' stubs in array keywords were updated to other value because we have entries with 'test' word in our data
TBD
> b2b up-selling products endpoint tests + dummy value update

- resources/environments/environments_api_b2b.json
- tests/api/b2b/glue/url_resolver_endpoints/negative.robot
- tests/api/b2b/glue/url_resolver_endpoints/positive.robot
create b2b tests for url-resolver endpoints
> create b2b tests for url-resolver endpoints

- resources/environments/environments_api_b2b.json
- tests/api/b2b/glue/stores_endpoints/negative.robot
- tests/api/b2b/glue/stores_endpoints/positive.robot
B2B tests for stores endpoints
> create b2b tests for stores endpoints

- resources/environments/environments_api_b2b.json
- tests/api/b2b/glue/access_token_endpoints/token/negative.robot
- tests/api/b2b/glue/access_token_endpoints/token/positive.robot
> create b2b tests for token endpoints

- resources/environments/environments_api_b2c.json
- tests/api/b2c/glue/utility_endpoints/stores/negative.robot
- tests/api/b2c/glue/utility_endpoints/stores/positive.robot
CC-16446  b2c stores endpoints
> b2c stores endpoints

- resources/environments/environments_api_b2b_mp.json
- tests/api/b2b_mp/glue/access_token_endpoints/access_tokens/negative.robot
- tests/api/b2b_mp/glue/access_token_endpoints/access_tokens/positive.robot
- tests/api/b2b_mp/glue/access_token_endpoints/refresh_tokens/negative.robot
- tests/api/b2b_mp/glue/access_token_endpoints/refresh_tokens/positive.robot
- tests/api/b2b_mp/glue/access_token_endpoints/token/negative.robot
- tests/api/b2b_mp/glue/access_token_endpoints/token/positive.robot
> Add B2B MP infra env

- resources/environments/environments_api_mp_b2b.json
- tests/api/mp_b2b/glue/return_endpoints/return_reasons/positive.robot
CC-16417: mp-b2b return reasons
> mp b2b return reasons

- resources/environments/environments_api_mp_b2b.json
- tests/api/mp_b2b/glue/utility_endpoints/url_resolver/negative.robot
- tests/api/mp_b2b/glue/utility_endpoints/url_resolver/positive.robot
CC-16462: URL resolver endpoints mp-b2b
> mp b2b folder changes

- resources/environments/environments_api_b2b.json
- resources/environments/environments_api_mp_b2b.json
- tests/api/b2b/glue/customer_endpoints/customers/positive.robot
- tests/api/mp_b2b/glue/customer_endpoints/addresses/negative.robot
- tests/api/mp_b2b/glue/customer_endpoints/addresses/positive.robot
- tests/api/mp_b2b/glue/customer_endpoints/customer_access/positive.robot
- tests/api/mp_b2b/glue/customer_endpoints/customer_confirmation/negative.robot
- tests/api/mp_b2b/glue/customer_endpoints/customer_confirmation/positive.robot
- tests/api/mp_b2b/glue/customer_endpoints/customer_forgotten_password/negative.robot
- tests/api/mp_b2b/glue/customer_endpoints/customer_forgotten_password/positive.robot
- tests/api/mp_b2b/glue/customer_endpoints/customer_password/negative.robot
- tests/api/mp_b2b/glue/customer_endpoints/customer_password/positive.robot
- tests/api/mp_b2b/glue/customer_endpoints/customer_restore_password/negative.robot
- tests/api/mp_b2b/glue/customer_endpoints/customer_restore_password/positive.robot
- tests/api/mp_b2b/glue/customer_endpoints/customers/negative.robot
- tests/api/mp_b2b/glue/customer_endpoints/customers/positive.robot
CC-16077 CC-16252 CC-16257 customer_endpoints
> CC-16077 CC-16252 CC-16257 customer_endpoints

- tests/api/b2b/glue/availability_endpoints/availability_notifications/positive.robot
- tests/api/mp_b2b/glue/availability_endpoints/availability_notifications/negative.robot
- tests/api/mp_b2b/glue/availability_endpoints/availability_notifications/positive.robot
> added mp-b2b availability-notifications

- resources/environments/environments_api_b2b.json
- tests/api/b2b/glue/returns_endpoints/return_reasons/positive.robot
> return-reasons-positive

- tests/api/mp_b2b/glue/concrete_products_endpoints/concrete_product_prices/negative.robot
- tests/api/mp_b2b/glue/concrete_products_endpoints/concrete_product_prices/positive.robot
Create mp-b2b-concrete-product-prices-endpoints-tests
> mp-b2b-concrete-products-prices-endpoints

- resources/environments/environments_api_mp_b2b.json
- tests/api/mp_b2b/glue/navigations_endpoints/navigations/negative.robot
- tests/api/mp_b2b/glue/navigations_endpoints/navigations/positive.robot
> CC-16327 navigation endpoints

- tests/api/mp_b2b/glue/category_endpoints/category_nodes/negative.robot
- tests/api/mp_b2b/glue/category_endpoints/category_nodes/positive.robot
CC-16152 mp b2b category nodes endpoints
> mp-b2b-category-nodes-endpoints

- tests/api/mp_b2b/glue/category_endpoints/category_trees/positive.robot
CC-16157   mp-b2b category trees
> mp-b2b category trees endpoints

- tests/api/mp_b2b/glue/content_endpoints/cms_pages/negative.robot
- tests/api/mp_b2b/glue/content_endpoints/cms_pages/positive.robot
- tests/api/mp_b2b/glue/content_endpoints/content_product_abstract_lists/negative.robot
- tests/api/mp_b2b/glue/content_endpoints/content_product_abstract_lists/positive.robot
> CC-16172 content endpoint

- tests/api/mp_b2b/glue/concrete_products_endpoints/concrete_product_availabilities/negative.robot
- tests/api/mp_b2b/glue/concrete_products_endpoints/concrete_product_availabilities/positive.robot
- tests/api/mp_b2b/glue/concrete_products_endpoints/concrete_product_image_sets/negative.robot
- tests/api/mp_b2b/glue/concrete_products_endpoints/concrete_product_image_sets/positive.robot
Create PR for
CC-16217: concrete-product-image-sets
CC-16212 concrete-product-availabilities
> CC-16217 CC-16212 concrete products endpoints

- tests/api/mp_b2b/glue/company_endpoints/company_roles/negative.robot
- tests/api/mp_b2b/glue/company_endpoints/company_roles/positive.robot
CC-16192: mp-b2b company roles endpoints
> mp-b2b company roles endpoints

- resources/environments/environments_api_mp_b2b.json
- tests/api/mp_b2b/glue/search_endpoints/catalog_search_suggestions/positive.robot
> mp-b2b-catalog-search-suggestions

- tests/api/mp_b2b/glue/content_endpoints/content_banners/negative.robot
- tests/api/mp_b2b/glue/content_endpoints/content_banners/positive.robot
> CC-16242 mp content_banners

- tests/api/mp_b2b/glue/general_product_endpoints/product_tax_sets/negative.robot
- tests/api/mp_b2b/glue/general_product_endpoints/product_tax_sets/positive.robot
CC-16377 Product tax sets endpoints
> mp-b2b-product-tax-sets

- tests/api/mp_b2b/glue/company_endpoints/companies/negative.robot
- tests/api/mp_b2b/glue/company_endpoints/companies/positive.robot
CC-16177 mp-b2b-company-endpoint
> mp-b2b-companies-endpoint

- tests/api/mp_b2b/glue/company_endpoints/company_business_unit/negative.robot
- tests/api/mp_b2b/glue/company_endpoints/company_business_unit/positive.robot
CC-16187: mp-b2b company business unit
> mp-b2b company business unit

- resources/environments/environments_api_b2b.json
- tests/api/b2b/glue/cart_endpoints/cart_permssion_groups/positive.robot
fix `carts/{cartId}?include=cart-permission-groups` endpoint regarding 
this bug  https://spryker.atlassian.net/browse/CC-16527 has been resolved
> fix tests for carts included cart-permission-groups

- tests/api/b2b/glue/abstract_product_endpoints/abstract_alternative_products/negative.robot
- tests/api/mp_b2b/glue/abstract_product_endpoints/abstract_alternative_products/negative.robot
- tests/api/mp_b2b/glue/abstract_product_endpoints/abstract_alternative_products/positive.robot
Task: https://spryker.atlassian.net/browse/CC-16047
TBD
> Mp-b2b abstract product endpoints

- tests/api/mp_b2b/glue/general_product_endpoints/related_products/negative.robot
- tests/api/mp_b2b/glue/general_product_endpoints/related_products/positive.robot
Related products endpoint tests were added for MP B2B env
> mp_b2b related products tests

- tests/api/b2b/glue/utility_endpoints/health_checks/positive.robot
- tests/api/mp_b2b/glue/utility_endpoints/health_checks/negative.robot
- tests/api/mp_b2b/glue/utility_endpoints/health_checks/positive.robot
Task: https://spryker.atlassian.net/browse/CC-16297
TBD
> Mp b2b health check endpoints

- tests/api/b2c/glue/agent_endpoints/agent_customer_search/negative.robot
- tests/api/b2c/glue/agent_endpoints/agent_customer_search/positive.robot
CC-16091: b2c agent-customer-search endpoint
> CC-16091: b2c agent-customer-search endpoint

- tests/api/mp_b2b/glue/concrete_products_endpoints/concrete_alternative_products/negative.robot
- tests/api/mp_b2b/glue/concrete_products_endpoints/concrete_alternative_products/positive.robot
mp-b2b-concrete-alternative-products-endpoints
> mp-b2b-concrete-alternative-products-endpoints

- tests/api/mp_b2b/glue/weight_unit_endpoints/product_measurement_units/negative.robot
- tests/api/mp_b2b/glue/weight_unit_endpoints/product_measurement_units/positive.robot
CC-16352-product-measurement-units endpoint
> mp-b2b-product-measurement-units

- tests/api/mp_b2b/glue/general_product_endpoints/product_reviews/negative.robot
- tests/api/mp_b2b/glue/general_product_endpoints/product_reviews/positive.robot
CC-16372     mp-b2b-product-reviews
> mp-b2b-product-reviews-endpoint

- tests/api/mp_b2b/glue/company_endpoints/company_business_unit_addresses/negative.robot
- tests/api/mp_b2b/glue/company_endpoints/company_business_unit_addresses/positive.robot
CC-16182: mp-b2b company business unit address
> mp b2b business unit address

- tests/api/mp_b2b/glue/cart_endpoints/cart_permssion_groups/negitive.robot
- tests/api/mp_b2b/glue/cart_endpoints/cart_permssion_groups/positive.robot
create tests for mp-b2b-cart-permission-groups
> create tests for mp-b2b-cart-permission-groups

- tests/api/mp_b2b/glue/agent_endpoints/agent_customer_impersonation_access_tokens/negative.robot
- tests/api/mp_b2b/glue/agent_endpoints/agent_customer_impersonation_access_tokens/positive.robot
create tests for mp-b2b-agent-customer-impersonation-access-tokens
> create tests for mp-b2b-agent-customer-impersonation-access-tokens

- resources/environments/environments_api_mp_b2b.json
- tests/api/mp_b2b/glue/cart_endpoints/shared-carts/negative.robot
- tests/api/mp_b2b/glue/cart_endpoints/shared-carts/positive.robot
create tests for mp-b2b-shared-carts
> create tests for mp-b2b-shared-carts

- tests/api/b2b/glue/general_product_endpoints/product_management_attributes/negative.robot
- tests/api/b2b/glue/general_product_endpoints/product_management_attributes/positive.robot
- tests/api/mp_b2b/glue/general_product_endpoints/product_management_attributes/negative.robot
- tests/api/mp_b2b/glue/general_product_endpoints/product_management_attributes/positive.robot
create tests for mp-b2b-product-management-attributes
> create tests for mp-b2b-product-management-attributes

- tests/api/b2b/glue/company_endpoints/company_user_access_tokens/negative.robot
- tests/api/b2b/glue/company_endpoints/company_user_access_tokens/positive.robot
- tests/api/mp_b2b/glue/company_endpoints/company_user_access_tokens/negative.robot
- tests/api/mp_b2b/glue/company_endpoints/company_user_access_tokens/positive.robot
create tests for mp-b2b-company-user-access-tokens
> create tests for mp-b2b-company-user-access-tokens

- tests/api/mp_b2b/glue/shopping_list_endpoints/shopping_lists/negative.robot
- tests/api/mp_b2b/glue/shopping_list_endpoints/shopping_lists/positive.robot
CC-16442   mp-b2b Shopping lists
> mp-b2b shopping lists endpoint

- resources/environments/environments_api_mp_b2c.json
- tests/api/mp_b2c/glue/access_token_endpoints/access_tokens/negative.robot
- tests/api/mp_b2c/glue/access_token_endpoints/access_tokens/positive.robot
- tests/api/mp_b2c/glue/access_token_endpoints/refresh_tokens/negative.robot
- tests/api/mp_b2c/glue/access_token_endpoints/refresh_tokens/positive.robot
> CC-16069 init mp_b2c

- tests/api/b2b/glue/company_endpoints/company_users/negative.robot
- tests/api/mp_b2b/glue/company_endpoints/company_users/negative.robot
- tests/api/mp_b2b/glue/company_endpoints/company_users/positive.robot
Mp-b2b: Added test scripts for company-users endpoints
> CC-16199: company-users endpoints

- tests/api/mp_b2b/glue/availability_endpoints/my_availability_notifications/negative.robot
- tests/api/mp_b2b/glue/availability_endpoints/my_availability_notifications/positive.robot
CC-16322  mp-b2b my availability notifications
> mp-b2b my availability notifications

- tests/api/mp_b2c/glue/agent_endpoints/agent_access_tokens/negative.robot
- tests/api/mp_b2c/glue/agent_endpoints/agent_access_tokens/positive.robot
CC-16083: mp-b2c agent access tokens
> mp-b2c agent access tokens

- tests/api/mp_b2c/glue/general_product_endpoints/product_tax_sets/negative.robot
- tests/api/mp_b2c/glue/general_product_endpoints/product_tax_sets/positive.robot
> mp-b2c-product-tax-sets

- tests/api/mp_b2c/glue/agent_endpoints/agent_customer_impersonation_access_tokens/negative.robot
- tests/api/mp_b2c/glue/agent_endpoints/agent_customer_impersonation_access_tokens/positive.robot
CC-16088: mp-b2c agent-customer-impersonation-access-tokens
> agent-endpoints agent customer impersonation access tokens

- resources/environments/environments_api_b2b.json
- tests/api/b2b/glue/configurable_bundle_endpoints/configurable_bundle/negative.robot
- tests/api/b2b/glue/configurable_bundle_endpoints/configurable_bundle/positive.robot
CC-16229 CC-16234 configurable_bundle_endpoints
> CC-16229 CC-16234 configurable_bundle_endpoints

- tests/api/mp_b2c/glue/general_product_endpoints/upselling_products/negative.robot
- tests/api/mp_b2c/glue/general_product_endpoints/upselling_products/positive.robot
https://spryker.atlassian.net/browse/CC-16458
upselling-products tests for mp-b2c demoshop
> mp-b2c-upselling-products-endpoints

- tests/api/mp_b2c/glue/concrete_products_endpoints/concrete_alternative_products/negative.robot
- tests/api/mp_b2c/glue/concrete_products_endpoints/concrete_alternative_products/positive.robot
CC-16208   mp b2c concrete alternative products
> mp-b2c-concrete-alternative-products

- resources/environments/environments_api_mp_b2c.json
- tests/api/mp_b2c/glue/general_product_endpoints/product_reviews/negative.robot
- tests/api/mp_b2c/glue/general_product_endpoints/product_reviews/positive.robot
CC-16373 mp-b2c product reviews
> mp-b2c-product-reviews

- tests/api/mp_b2c/glue/returns_endpoints/return_reasons/positive.robot
CC-16418: mp-b2c return reasons endpoint
> mp-b2c return reasons endpoint

- tests/api/mp_b2c/glue/agent_endpoints/agent_customer_search/negative.robot
- tests/api/mp_b2c/glue/agent_endpoints/agent_customer_search/positive.robot
CC-16093: mp-b2c agent customer search
> mp-b2c agent customer search

- tests/api/mp_b2c/glue/customer_endpoints/customer_restore_password/negative.robot
- tests/api/mp_b2c/glue/customer_endpoints/customer_restore_password/positive.robot
CC-16273 customer-restore-password-endpoint
> mp-b2c-customer-restore-password-endpoint

- resources/environments/environments_api_mp_b2c.json
- tests/api/mp_b2c/glue/general_product_endpoints/product_management_attributes/negative.robot
- tests/api/mp_b2c/glue/general_product_endpoints/product_management_attributes/positive.robot
CC-16348 product-management-attributes-endpoint
> mp-b2c-product-management-attributes-endpoint

- tests/api/mp_b2c/glue/abstract_product_endpoints/abstract_product_image_sets/negative.robot
- tests/api/mp_b2c/glue/abstract_product_endpoints/abstract_product_image_sets/positive.robot
positive and negative tests
TBD
> mp-b2c-abstract-product-image-sets

- tests/api/mp_b2c/glue/general_product_endpoints/related_products/negative.robot
- tests/api/mp_b2c/glue/general_product_endpoints/related_products/positive.robot
CC-16413 m b2c related products endpoint
> mp-b2c-related-products

- tests/api/mp_b2c/glue/concrete_products_endpoints/concrete_product_availabilities/negative.robot
- tests/api/mp_b2c/glue/concrete_products_endpoints/concrete_product_availabilities/positive.robot
mp-b2c-concrete-product-availabilities-endpoints
https://spryker.atlassian.net/browse/CC-16213
> mp-b2c-concrete-product-availabilities-endpoints

- tests/api/mp_b2c/glue/concrete_products_endpoints/concrete_product_image_sets/negative.robot
- tests/api/mp_b2c/glue/concrete_products_endpoints/concrete_product_image_sets/positive.robot
mp-b2c-concrete-product-image-sets-endpoints-tests
https://spryker.atlassian.net/browse/CC-16218
> mp-b2c-concrete-product-image-sets-endpoints

- resources/environments/environments_api_mp_b2c.json
- tests/api/mp_b2c/glue/search_endpoints/catalog_search_suggestions/positive.robot
CC-16148: mp-b2c catalog search suggestions
> mp-b2c catalog search suggestions

- tests/api/mp_b2c/glue/abstract_product_endpoints/abstract_alternative_products/negative.robot
- tests/api/mp_b2c/glue/abstract_product_endpoints/abstract_alternative_products/positive.robot
CC-16048: mp-b2c abstract alternative products endpoints
> mp-b2c abstract alternative products endpoints

- resources/environments/environments_api_mp_b2b.json
- tests/api/mp_b2b/glue/checkout_endpoints/checkout/negative.robot
- tests/api/mp_b2b/glue/checkout_endpoints/checkout/positive.robot
- Refactored tests for mp_b2b
- Added 'merchantReference' for checkout POST request
> added checkout for mp_b2b

- resources/environments/environments_api_mp_b2c.json
- tests/api/mp_b2c/glue/bundle_endpoints/bundled_products/negative.robot
- tests/api/mp_b2c/glue/bundle_endpoints/bundled_products/positive.robot
CC-16123: mp-b2c bundled products endpoints
> mp-b2c bundled endpoints

- resources/environments/environments_api_mp_b2c.json
- tests/api/mp_b2c/glue/abstract_product_endpoints/abstract_products/negative.robot
- tests/api/mp_b2c/glue/abstract_product_endpoints/abstract_products/positive.robot
mp-b2c-abstract-products-endpoint
https://spryker.atlassian.net/browse/CC-16068
> mp-b2c-abstract-products-endpoint

- resources/environments/environments_api_b2c.json
- tests/api/b2c/glue/access_token_endpoints/token/negative.robot
- tests/api/b2c/glue/access_token_endpoints/token/positive.robot
> CC-16451: create b2c tests for token endpoints

- tests/api/b2c/glue/customer_endpoints/customer_restore_password/negative.robot
- tests/api/b2c/glue/customer_endpoints/customer_restore_password/positive.robot
positive and negative tests
TBD
> b2c-customer-restore-password

- tests/api/mp_b2c/glue/abstract_product_endpoints/abstract_product_prices/negative.robot
- tests/api/mp_b2c/glue/abstract_product_endpoints/abstract_product_prices/positive.robot
positive and negative tests added
TBD
> mp-b2c-abstract-product-prices

- resources/environments/environments_api_mp_b2c.json
- tests/api/mp_b2c/glue/wishlist_endpoints/wishlist_items/negative.robot
- tests/api/mp_b2c/glue/wishlist_endpoints/wishlist_items/positvie.robot
CC-16473  mp-b2c-wishlist-items-endpoint
> mp-b2c-wishlist-items-endpoints

- resources/environments/environments_api_mp_b2c.json
- tests/api/mp_b2c/glue/product_offer_endpoints/product_offer_availabilities/negative.robot
- tests/api/mp_b2c/glue/product_offer_endpoints/product_offer_availabilities/positive.robot
mp-b2c-product-offer-availabilities-endpoint-tests
https://spryker.atlassian.net/browse/CC-16358
> mp-b2c-product-offer-availabilities-endpoint-tests

- resources/environments/environments_api_mp_b2c.json
- tests/api/mp_b2c/glue/concrete_products_endpoints/concrete_products/negative.robot
- tests/api/mp_b2c/glue/concrete_products_endpoints/concrete_products/positive.robot
mp-b2c-concrete-products-endpoint
https://spryker.atlassian.net/browse/CC-16228
> mp-b2c-concrete-products-endpoint

- resources/environments/environments_api_mp_b2c.json
- tests/api/mp_b2c/glue/order_endpoints/orders/negative.robot
- tests/api/mp_b2c/glue/order_endpoints/orders/positive.robot
https://spryker.atlassian.net/browse/CC-16338
mp-b2c-orders-endpoints
> mp-b2c-orders-endpoints-tests

- resources/environments/environments_api_b2b.json
- resources/environments/environments_api_mp_b2b.json
- tests/api/b2b/glue/shopping_list_endpoints/shopping_list_items/negative.robot
- tests/api/b2b/glue/shopping_list_endpoints/shopping_list_items/positive.robot
- tests/api/mp_b2b/glue/shopping_list_endpoints/shopping_list_items/negative.robot
- tests/api/mp_b2b/glue/shopping_list_endpoints/shopping_list_items/positive.robot
> create tests for mp b2b shopping list items

- tests/api/b2c/glue/availability_endpoints/my_availability_notifications/negative.robot
- tests/api/b2c/glue/availability_endpoints/my_availability_notifications/positive.robot
positive and negative tests
TBD
> b2c-my-availability-notifications

- tests/api/mp_b2c/glue/customer_endpoints/customer_confirmation/negative.robot
- tests/api/mp_b2c/glue/customer_endpoints/customer_confirmation/positive.robot
mp-b2c-customer-confirmation-endpoints
https://spryker.atlassian.net/browse/CC-16258
> mp-b2c-customer-confirmation-endpoint-tests

- resources/environments/environments_api_mp_b2c.json
- tests/api/mp_b2c/glue/search_endpoints/catalog_search/negative.robot
- tests/api/mp_b2c/glue/search_endpoints/catalog_search/positive.robot
CC-16143: mp-b2c catalog search
> mp-b2c catalog search

- tests/api/b2c/glue/general_product_endpoints/product_tax_sets/negative.robot
- tests/api/b2c/glue/general_product_endpoints/product_tax_sets/positive.robot
> CC-16376: b2c product tax set

- tests/api/mp_b2b/glue/abstract_product_endpoints/abstract_product_availabilities/negative.robot
- tests/api/mp_b2b/glue/abstract_product_endpoints/abstract_product_availabilities/positive.robot
CC-16052 mp-b2b-abstract-products-availabilities
> mp-b2b-abstract-products-availabilities

- tests/api/mp_b2c/glue/utility_endpoints/health_checks/negative.robot
- tests/api/mp_b2c/glue/utility_endpoints/health_checks/positive.robot
CC-16298   mp-b2c health check endpoint
> mp-b2c-health-check-endpoint

- tests/api/b2c/glue/agent_endpoints/agent_customer_impersonation_access_tokens/negative.robot
- tests/api/b2c/glue/agent_endpoints/agent_customer_impersonation_access_tokens/positive.robot
CC-16084: b2c agent customer impersonation access token endpoints
> b2c agent customer impersonation access token endpoints

- tests/api/b2c/glue/customer_endpoints/customer_confirmation/negative.robot
- tests/api/b2c/glue/customer_endpoints/customer_confirmation/positive.robot
https://spryker.atlassian.net/browse/CC-16256
b2c-customer-confirmation-endpoints
> b2c-customer-confirmation-endpoints

- resources/environments/environments_api_b2c.json
- tests/api/b2c/glue/configured_bundles_endpoints/guest_configured_bundles/negative.robot
- tests/api/b2c/glue/configured_bundles_endpoints/guest_configured_bundles/positive.robot
Tests created for POST, PATCH, EDIT methods of guest configured bundles endpoint
> B2C guest configured bundles endpoint

- tests/api/b2c/glue/utility_endpoints/health_checks/negative.robot
- tests/api/b2c/glue/utility_endpoints/health_checks/positive.robot
> b2c health checks

- resources/environments/environments_api_mp_b2c.json
- tests/api/mp_b2c/glue/returns_endpoints/returns/negative.robot
- tests/api/mp_b2c/glue/returns_endpoints/returns/positive.robot
CC-16423 mpb2c return endpoints
> mp-b2c return endpoints

- resources/environments/environments_api_b2c.json
- tests/api/b2c/glue/order_endpoints/orders/negative.robot
- tests/api/b2c/glue/order_endpoints/orders/positive.robot
https://spryker.atlassian.net/browse/CC-16336
b2c-orders-endpoints-tests
> b2c-orders-endpoint-tests

- resources/common/common_yves.robot
- resources/pages/yves/yves_usercentrics_form.robot
- resources/pages/zed/zed_aop_usercentrics_details_page.robot
- resources/steps/bazaarvoice_steps.robot
- resources/steps/usercentrics_steps.robot
- tests/e2e/aop/usercentrics_pbc.robot
Ticket: https://spryker.atlassian.net/browse/APPS-3879
> APPS-3879 Implemented Usercentrics e2e test

- resources/environments/environments_api_b2c.json
- tests/api/b2c/glue/configurable_bundle_endpoints/configurable_bundle/negative.robot
- tests/api/b2c/glue/configurable_bundle_endpoints/configurable_bundle/positive.robot
> CC-16236 configurable bundle

- resources/environments/environments_api_b2c.json
- tests/api/b2c/glue/cart_endpoints/carts/positive.robot
- tests/api/b2c/glue/cart_endpoints/guest-carts/positive.robot
- tests/api/b2c/glue/discount_endpoints/vouchers/negative.robot
- tests/api/b2c/glue/discount_endpoints/vouchers/positive.robot
Created the bug ticket for Swagger: https://spryker.atlassian.net/browse/CC-16744
> CC-16466-b2c-vouchers

- resources/environments/environments_api_b2c.json
- tests/api/b2c/glue/configured_bundles_endpoints/configured_bundles_templates/negative.robot
- tests/api/b2c/glue/configured_bundles_endpoints/configured_bundles_templates/positive.robot
CC-16231: b2c-configurable-bundle-templates
> b2c-configurable-bundle-templates

- resources/common/common.robot
Added device to the Suite Setup
> DQIB-2994-device-refactoring

- resources/environments/environments_api_mp_b2c.json
- tests/api/mp_b2c/glue/discount_endpoints/vouchers/negative.robot
- tests/api/mp_b2c/glue/discount_endpoints/vouchers/positive.robot
https://spryker.atlassian.net/browse/CC-16468
> mp-b2c-voucher-endpoints-tests

- resources/common/common_yves.robot
- resources/steps/checkout_steps.robot
- resources/steps/customer_account_steps.robot
- resources/steps/shopping_carts_steps.robot
- tests/smoke/smoke_b2c.robot
- Updated tests to match current state/data of demoshop
- Fixed some flaky tests - added explicit waits to rise stability
> B2C smoke tests fixes

- resources/environments/environments_api_suite.json
- tests/api/suite_nonsplit/glue/abstract_product_endpoints/abstract_alternative_products/negative.robot
- tests/api/suite_nonsplit/glue/abstract_product_endpoints/abstract_alternative_products/positive.robot
- tests/api/suite_nonsplit/glue/abstract_product_endpoints/abstract_product_availabilities/negative.robot
- tests/api/suite_nonsplit/glue/abstract_product_endpoints/abstract_product_availabilities/positive.robot
- tests/api/suite_nonsplit/glue/abstract_product_endpoints/abstract_product_image_sets/negative.robot
- tests/api/suite_nonsplit/glue/abstract_product_endpoints/abstract_product_image_sets/positive.robot
- tests/api/suite_nonsplit/glue/abstract_product_endpoints/abstract_product_prices/negative.robot
- tests/api/suite_nonsplit/glue/abstract_product_endpoints/abstract_product_prices/positive.robot
- tests/api/suite_nonsplit/glue/abstract_product_endpoints/abstract_products/negative.robot
- tests/api/suite_nonsplit/glue/abstract_product_endpoints/abstract_products/positive.robot
- tests/api/suite_nonsplit/glue/access_token_endpoints/access_tokens/negative.robot
- tests/api/suite_nonsplit/glue/access_token_endpoints/access_tokens/positive.robot
- tests/api/suite_nonsplit/glue/access_token_endpoints/refresh_tokens/negative.robot
- tests/api/suite_nonsplit/glue/access_token_endpoints/refresh_tokens/positive.robot
- tests/api/suite_nonsplit/glue/agent_endpoints/agent_access_tokens/negative.robot
- tests/api/suite_nonsplit/glue/agent_endpoints/agent_access_tokens/positive.robot
- tests/api/suite_nonsplit/glue/content_endpoints/content_product_abstract_lists/negative.robot
- tests/api/suite_nonsplit/glue/content_endpoints/content_product_abstract_lists/positive.robot
- tests/api/suite_nonsplit/glue/customer_endpoints/addresses/negative.robot
- tests/api/suite_nonsplit/glue/customer_endpoints/addresses/positive.robot
https://spryker.atlassian.net/browse/CC-16852
Refactor api_suite environment variables file to match the new format
> refactor_non_split_env_and_tests

- resources/common/common.robot
- resources/common/common_yves.robot
- resources/common/common_zed.robot
- resources/environments/environments_b2b.json
- resources/pages/yves/yves_checkout_address_page.robot
- resources/pages/yves/yves_checkout_summary_page.robot
- resources/pages/yves/yves_header_section.robot
- resources/steps/agent_assist_steps.robot
- resources/steps/catalog_steps.robot
- resources/steps/checkout_steps.robot
- resources/steps/header_steps.robot
- resources/steps/order_history_steps.robot
- resources/steps/product_set_steps.robot
- resources/steps/request_for_quote_steps.robot
- resources/steps/shopping_carts_steps.robot
- tests/smoke/smoke_b2b.robot
- tests/smoke/smoke_b2c.robot
Made some changes to rise tests stability on stage:
- Added some explicit waits
- User submitting on zed and address selection on Yves used to be very unstable and waits haven't helped - so had to add additional attempts there
TBD
> B2B, B2C smoke tests refactoring to improve stability on stage

- resources/environments/environments_api_suite.json
- tests/api/suite_nonsplit/glue/company_endpoints/companies/negative.robot
- tests/api/suite_nonsplit/glue/company_endpoints/companies/positive.robot
https://spryker.atlassian.net/browse/CC-16791 - Companies endpoint
> suite-nonsplit-companies-endpoint

- tests/api/suite_nonsplit/glue/company_endpoints/company_roles/negative.robot
- tests/api/suite_nonsplit/glue/company_endpoints/company_roles/positive.robot
https://spryker.atlassian.net/browse/CC-16794 - Suite-nonsplit company roles
> suite-nonsplit-company-roles

- resources/environments/environments_api_suite.json
- tests/api/suite_nonsplit/glue/category_endpoints/category_nodes/negative.robot
- tests/api/suite_nonsplit/glue/category_endpoints/category_nodes/positive.robot
https://spryker.atlassian.net/browse/CC-16786   
suite-nonsplit-category-nodes-endpoints
> suite-nonsplit-category-nodes-endpoints

- tests/api/suite_nonsplit/glue/company_endpoints/company_user_access_tokens/negative.robot
- tests/api/suite_nonsplit/glue/company_endpoints/company_user_access_tokens/positive.robot
https://spryker.atlassian.net/browse/CC-16795 - suit-nonsplit-company_user_access_tokens
> suit-nonsplit-company_user_access_tokens

- resources/environments/environments_api_suite.json
- tests/api/suite_nonsplit/glue/merchant_endpoints/merchant_addresses/negative.robot
- tests/api/suite_nonsplit/glue/merchant_endpoints/merchant_addresses/positive.robot
- tests/api/suite_nonsplit/glue/merchant_endpoints/merchant_opening_hours/negative.robot
- tests/api/suite_nonsplit/glue/merchant_endpoints/merchant_opening_hours/positive.robot
- tests/api/suite_nonsplit/glue/merchant_endpoints/merchants/negative.robot
- tests/api/suite_nonsplit/glue/merchant_endpoints/merchants/positive.robot
https://spryker.atlassian.net/browse/CC-16817
https://spryker.atlassian.net/browse/CC-16818
https://spryker.atlassian.net/browse/CC-16819
> non-split-merchant-endpoints-tests

- resources/environments/environments_api_suite.json
- tests/api/suite_nonsplit/glue/customer_endpoints/customer_confirmation/negative.robot
- tests/api/suite_nonsplit/glue/customer_endpoints/customer_confirmation/positive.robot
- tests/api/suite_nonsplit/glue/customer_endpoints/customer_forgotten_password/negative.robot
- tests/api/suite_nonsplit/glue/customer_endpoints/customer_forgotten_password/positive.robot
- tests/api/suite_nonsplit/glue/customer_endpoints/customer_password/negative.robot
- tests/api/suite_nonsplit/glue/customer_endpoints/customer_password/positive.robot
- tests/api/suite_nonsplit/glue/customer_endpoints/customer_restore_password/negative.robot
- tests/api/suite_nonsplit/glue/customer_endpoints/customer_restore_password/positive.robot
customer-restore-password https://spryker.atlassian.net/browse/CC-16810
customer-password https://spryker.atlassian.net/browse/CC-16809
customer-confirmation https://spryker.atlassian.net/browse/CC-16807
customer-forgotten-password https://spryker.atlassian.net/browse/CC-16808
> non-split-customer-endpoints-tests

- tests/api/suite_nonsplit/glue/general_product_endpoints/product_tax_sets/negative.robot
- tests/api/suite_nonsplit/glue/general_product_endpoints/product_tax_sets/positive.robot
https://spryker.atlassian.net/browse/CC-16831 - product-tax-sets
> suite-nonsplit-product-tax-sets

- resources/environments/environments_api_suite.json
- tests/api/suite_nonsplit/glue/customer_endpoints/customer_access/negative.robot
- tests/api/suite_nonsplit/glue/customer_endpoints/customer_access/positive.robot
CC-16806: suite-nonsplit-customer-access
> suite-nonsplit-customer-access

- resources/environments/environments_api_suite.json
- tests/api/suite_nonsplit/glue/general_product_endpoints/product_labels/negative.robot
- tests/api/suite_nonsplit/glue/general_product_endpoints/product_labels/positive.robot
https://spryker.atlassian.net/browse/CC-16824
> non-split-product-labels-endpoint

- resources/environments/environments_api_suite.json
- tests/api/suite_nonsplit/glue/cart_endpoints/guest_carts/negative.robot
- tests/api/suite_nonsplit/glue/cart_endpoints/guest_carts/positive.robot
https://spryker.atlassian.net/browse/CC-16813
guest-cart-endpoint
> non-split-cart-guest-endpoint

- tests/api/suite_nonsplit/glue/availability_endpoints/availability_notifications/negative.robot
- tests/api/suite_nonsplit/glue/availability_endpoints/availability_notifications/positive.robot
CC-16779: suite-nonsplit-availability-endpoints
> suite-nonsplit-availability-endpoints

- resources/environments/environments_api_suite.json
- tests/api/suite_nonsplit/glue/concrete_products_endpoints/concrete_product_availabilities/negative.robot
- tests/api/suite_nonsplit/glue/concrete_products_endpoints/concrete_product_availabilities/positive.robot
CC-16798: suite-nonsplit-concrete-product-availabilities
> suite-nonsplit-concrete-product-availabilities

- resources/environments/environments_api_suite.json
- tests/api/suite_nonsplit/glue/bundle_endpoints/bundled_products/negative.robot
- tests/api/suite_nonsplit/glue/bundle_endpoints/bundled_products/positive.robot
CC-16780: suite-nonsplit-bundled-products
> suite-nonsplit-bundled-products

- resources/environments/environments_api_suite.json
- tests/api/suite_nonsplit/glue/agent_endpoints/agent_customer_search/negative.robot
- tests/api/suite_nonsplit/glue/agent_endpoints/agent_customer_search/positive.robot
CC-16774: suite nonsplit agent customer search
> suite nonsplit agent customer search

- tests/api/suite_nonsplit/glue/concrete_products_endpoints/concrete_alternative_products/negative.robot
- tests/api/suite_nonsplit/glue/concrete_products_endpoints/concrete_alternative_products/positive.robot
CC-16797: suite-nonsplit-concrete-alternative-products
> suite-nonsplit-concrete-alternative-products

- tests/api/suite_nonsplit/glue/navigation_endpoints/navigations/negative.robot
- tests/api/suite_nonsplit/glue/navigation_endpoints/navigations/positive.robot
CC-16821: suite-nonsplit-navigations-endpoint
> suite-nonsplit-navigations-endpoint

- resources/environments/environments_api_suite.json
- tests/api/suite_nonsplit/glue/checkout_endpoints/checkout_data/negative.robot
- tests/api/suite_nonsplit/glue/checkout_endpoints/checkout_data/positive.robot
https://spryker.atlassian.net/browse/CC-16789
> non-split-checkout-data-endpoint-tests

- tests/api/suite_nonsplit/glue/utility_endpoints/health_checks/negative.robot
- tests/api/suite_nonsplit/glue/utility_endpoints/health_checks/positive.robot
https://spryker.atlassian.net/browse/CC-16815 - suite-nonsplit-health-checks
> suite-nonsplit-health-checks

- resources/environments/environments_api_suite.json
- tests/api/suite_nonsplit/glue/customer_endpoints/customers/negative.robot
- tests/api/suite_nonsplit/glue/customer_endpoints/customers/positive.robot
https://spryker.atlassian.net/browse/CC-16811 - Customers
> suite-nonsplit-customers

- resources/environments/environments_api_suite.json
- tests/api/suite_nonsplit/glue/agent_endpoints/agent_customer_impersonation_access_tokens/negative.robot
- tests/api/suite_nonsplit/glue/agent_endpoints/agent_customer_impersonation_access_tokens/positive.robot
CC-16773: agent customer impersonation access tokens
> agent customer impersonation access tokens

- resources/environments/environments_api_suite.json
- tests/api/suite_nonsplit/glue/general_product_endpoints/upselling_products/negative.robot
- tests/api/suite_nonsplit/glue/general_product_endpoints/upselling_products/positive.robot
https://spryker.atlassian.net/browse/CC-16847  
suite-nonsplit-upselling-products
> suite-nonsplit-upselling-products

- resources/environments/environments_api_suite.json
- tests/api/suite_nonsplit/glue/cart_endpoints/cart_items/negative.robot
- tests/api/suite_nonsplit/glue/cart_endpoints/cart_items/positive.robot
https://spryker.atlassian.net/browse/CC-16299     suite-nonsplit-cart-items
> suite-nonsplit-cart-items

- tests/api/suite_nonsplit/glue/customer_endpoints/addresses/negative.robot
> suite-nonsplit-addresses-CC-16726-resolved

- tests/api/suite_nonsplit/glue/abstract_product_endpoints/abstract_alternative_products/negative.robot
- tests/api/suite_nonsplit/glue/abstract_product_endpoints/abstract_product_image_sets/negative.robot
- tests/api/suite_nonsplit/glue/agent_endpoints/agent_access_tokens/negative.robot
https://spryker.atlassian.net/browse/CC-16767
https://spryker.atlassian.net/browse/CC-16765
https://spryker.atlassian.net/browse/CC-16772
added new test-case
> added new test cases in endpoints

- resources/environments/environments_b2c.json
- resources/pages/yves/yves_agent_assist_page.robot
- resources/steps/agent_assist_steps.robot
- resources/steps/order_history_steps.robot
- tests/features/agent_assist.robot
- tests/smoke/smoke_b2b.robot
- tests/smoke/smoke_b2c.robot
- tests/smoke/smoke_mp_b2b.robot
- tests/smoke/smoke_suite_nonsplit.robot
https://spryker.atlassian.net/browse/CC-21836
- Impersonate / unimpersonate as a customer
- Place an order for a customer
> smoke-b2c- agent assist

- resources/environments/environments_b2b.json
- tests/smoke/smoke_b2b.robot
https://spryker.atlassian.net/browse/CC-21648 smoke-b2b-shared-cart-with-read-only-perms
> smoke-b2b-shared-cart-with-read-only-perms

- resources/environments/environments_api_b2c.json
- tests/api/b2c/glue/agent_endpoints/agent_access_tokens/positive.robot
- tests/api/b2c/glue/checkout_endpoints/checkout/negative.robot
- tests/api/b2c/glue/checkout_endpoints/checkout_data/positive.robot
- tests/api/b2c/glue/search_endpoints/catalog_search/positive.robot
- tests/api/b2c/glue/utility_endpoints/health_checks/negative.robot
> Fixed api b2c tests that failed

- resources/environments/environments_api_mp_b2b.json
- tests/api/mp_b2b/glue/bundle_endpoints/bundled_products/positive.robot
- tests/api/mp_b2b/glue/category_endpoints/category_trees/positive.robot
- tests/api/mp_b2b/glue/concrete_products_endpoints/concrete_product_availabilities/positive.robot
- tests/api/mp_b2b/glue/customer_endpoints/customers/negative.robot
- tests/api/mp_b2b/glue/discount_endpoints/vouchers/negative.robot
- tests/api/mp_b2b/glue/product_offer_endpoints/product_offer_availabilities/negative.robot
- tests/api/mp_b2b/glue/product_offer_endpoints/product_offer_availabilities/positive.robot
- tests/api/mp_b2b/glue/product_offer_endpoints/product_offer_prices/negative.robot
- tests/api/mp_b2b/glue/product_offer_endpoints/product_offers/positive.robot
- tests/api/mp_b2b/glue/return_endpoints/returns/positive.robot
- tests/api/mp_b2b/glue/shopping_list_endpoints/shopping_list_items/negative.robot
> Fixed b2b-mp api tests that failed

- tests/api/b2c/glue/access_token_endpoints/refresh_tokens/negative.robot
Change attribute `refreshToken` assigned to `access_token` variable to be `accessToken`
> Fix attribute of variable in refresh tokens negative tests

- tests/api/b2b/glue/access_token_endpoints/refresh_tokens/negative.robot
- tests/api/b2b/glue/agent_endpoints/agent_customer_impersonation_access_tokens/negative.robot
- tests/api/b2b/glue/bundle_endpoints/bundled_products/negative.robot
- tests/api/b2b/glue/bundle_endpoints/bundled_products/positive.robot
- tests/api/b2b/glue/cart_endpoints/items/positive.robot
- tests/api/b2b/glue/checkout_endpoints/checkout/negative.robot
- tests/api/b2b/glue/company_endpoints/company_users/negative.robot
- tests/api/b2b/glue/configurable_bundle_endpoints/configurable_bundle/positive.robot
- tests/api/b2b/glue/customer_endpoints/customers/negative.robot
- tests/api/b2b/glue/discount_endpoints/vouchers/positive.robot
- tests/api/b2b/glue/general_product_endpoints/product_reviews/negative.robot
- tests/api/b2b/glue/general_product_endpoints/product_reviews/positive.robot
- tests/api/b2b/glue/search_endpoints/catalog_search/negative.robot
- tests/api/b2b/glue/shopping_list_endpoints/shopping_list_items/negative.robot
- tests/api/b2b/glue/shopping_list_endpoints/shopping_lists/positive.robot
> Updated tests for b2b-demoshop

- resources/environments/environments_api_mp_b2c.json
- tests/api/mp_b2c/glue/abstract_product_endpoints/abstract_alternative_products/positive.robot
- tests/api/mp_b2c/glue/abstract_product_endpoints/abstract_products/positive.robot
- tests/api/mp_b2c/glue/access_token_endpoints/refresh_tokens/negative.robot
- tests/api/mp_b2c/glue/agent_endpoints/agent_access_tokens/negative.robot
- tests/api/mp_b2c/glue/agent_endpoints/agent_access_tokens/positive.robot
- tests/api/mp_b2c/glue/agent_endpoints/agent_customer_impersonation_access_tokens/negative.robot
- tests/api/mp_b2c/glue/bundle_endpoints/bundled_products/negative.robot
- tests/api/mp_b2c/glue/bundle_endpoints/bundled_products/positive.robot
- tests/api/mp_b2c/glue/checkout_endpoints/checkout/negative.robot
- tests/api/mp_b2c/glue/concrete_products_endpoints/concrete_product_availabilities/positive.robot
- tests/api/mp_b2c/glue/general_product_endpoints/product_reviews/negative.robot
- tests/api/mp_b2c/glue/general_product_endpoints/product_reviews/positive.robot
- tests/api/mp_b2c/glue/product_offer_endpoints/product_offer_availabilities/negative.robot
- tests/api/mp_b2c/glue/product_offer_endpoints/product_offer_prices/negative.robot
- tests/api/mp_b2c/glue/product_offer_endpoints/product_offers/positive.robot
- tests/api/mp_b2c/glue/search_endpoints/catalog_search/negative.robot
- tests/api/mp_b2c/glue/search_endpoints/catalog_search/positive.robot
- tests/api/mp_b2c/glue/search_endpoints/catalog_search_suggestions/positive.robot
- tests/api/mp_b2c/glue/utility_endpoints/url_resolver/positive.robot
- tests/api/mp_b2c/glue/wishlist_endpoints/wishlist_items/positive.robot
- tests/api/mp_b2c/glue/wishlist_endpoints/wishlists/negative.robot
> Updated tests for b2c-mp

- tests/api/b2b/glue/category_endpoints/category_nodes/positive.robot
- tests/api/b2c/glue/category_endpoints/category_nodes/positive.robot
- tests/api/mp_b2b/glue/category_endpoints/category_nodes/positive.robot
- tests/api/mp_b2c/glue/category_endpoints/category_nodes/positive.robot
- tests/api/suite_nonsplit/glue/category_endpoints/category_nodes/positive.robot
https://spryker.atlassian.net/browse/CC-11134
bug-11134 updated test cases of category nodes
> bug-11134-category-node

- resources/environments/environments_api_suite.json
- tests/api/suite_nonsplit/glue/concrete_products_endpoints/concrete_product_image_sets/negative.robot
- tests/api/suite_nonsplit/glue/concrete_products_endpoints/concrete_product_image_sets/positive.robot
Ticket ID: 
https://spryker.atlassian.net/browse/CC-16799
Fixed Bug ID: https://spryker.atlassian.net/browse/CC-20963
1. Multiple image set data added.
2. Removed duplicate test data from env_api_suite.json
> suite-nonsplit-concrete-product-image-sets-bug-fixed

- resources/common/common_api.robot
- resources/environments/environments_api_suite.json
- tests/api/suite/bapi/example_endpoints/example/positive.robot
added new example of the bapi API test
> new example of the bapi API test

- tests/api/suite/glue/discount_endpoints/vouchers/positive.robot
- tests/api/suite/glue/order_endpoints/orders/positive.robot
- tests/api/suite/glue/search_endpoints/catalog_search/positive.robot
- tests/api/suite/glue/wishlist_endpoints/wishlist_items/positive.robot
disable failing suite api tests
> disable failing suite api tests

- tests/api/b2c/glue/abstract_product_endpoints/abstract_alternative_products/negative.robot
> Add one more negative test to /b2c/glue/abstract_product_endpoints/abstract_alternative_products/negative.robot

- tests/api/suite/glue/configurable_bundle_endpoints/configurable_bundle/negative.robot
- tests/api/suite/glue/configurable_bundle_endpoints/configurable_bundle/positive.robot
skiped API tests for https://spryker.atlassian.net/browse/CC-23359 as tests use string in quantity instead of int
> hotfix for CC-23359

- tests/api/suite/glue/checkout_endpoints/checkout/positive.robot
- tests/api/suite/glue/checkout_endpoints/checkout_data/positive.robot
> commit out several checkout tests

- tests/api/suite/glue/checkout_endpoints/checkout/positive.robot
> fix tests on checkout

- resources/common/common_api.robot
- tests/api/suite/glue/checkout_endpoints/checkout/positive.robot
- tests/api/suite/glue/checkout_endpoints/checkout_data/negative.robot
- tests/api/suite/glue/checkout_endpoints/checkout_data/positive.robot
> fix additional tests

- resources/common/common_api.robot
> remove log

- resources/common/common_api.robot
- resources/environments/environments_api_b2b.json
- resources/environments/environments_api_b2c.json
- resources/environments/environments_api_mp_b2b.json
- resources/environments/environments_api_mp_b2c.json
- resources/environments/environments_api_suite.json
- tests/api/suite/glue/cart_endpoints/cart_codes/negative.robot
Here is the fix for method "Connect to DB" new port for postgres added to suite-nonsplit
> Suite nonsplit port for postgres

- resources/common/common.robot
- resources/common/common_yves.robot
- resources/environments/environments_ui_b2b.json
- resources/environments/environments_ui_b2c.json
- resources/environments/environments_ui_mp_b2b.json
- resources/environments/environments_ui_mp_b2c.json
- resources/environments/environments_ui_suite.json
- resources/steps/shopping_carts_steps.robot
- resources/steps/shopping_lists_steps.robot
- tests/ui/e2e/e2e_b2b.robot
- tests/ui/e2e/e2e_b2c.robot
- tests/ui/e2e/e2e_mp_b2c.robot
- updated env variables to follow the same pattern
- extended SuiteSetup method to support cli input for the env variables
> Introduce env variables cli support

- tests/api/mp_b2b/glue/return_endpoints/returns/positive.robot
> skip-due-to-refactoring-return-tests

- tests/api/mp_b2b/glue/return_endpoints/returns/positive.robot
> B2b mp return

- tests/api/b2b/glue/cart_endpoints/shared_carts/negative.robot
- tests/api/b2b/glue/company_endpoints/company_users/positive.robot
- tests/api/mp_b2b/glue/cart_endpoints/shared_carts/negative.robot
- tests/api/mp_b2b/glue/company_endpoints/company_users/positive.robot
Hotfix for failing CI tests. 
- [x ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md
> skip 2 failing tests due to refactoring

- resources/common/common.robot
- resources/common/common_api.robot
- optimized common keywords to support cli arguments
- added fallback from item groupKey to item SKU for cart enpoints
> CLI optimization and fallback to sku in api test

- resources/common/common_api.robot
- resources/environments/environments_api_mp_b2b.json
- tests/api/mp_b2b/glue/abstract_product_endpoints/abstract_product_availabilities/positive.robot
- tests/api/mp_b2b/glue/customer_endpoints/customer_restore_password/positive.robot
- tests/api/mp_b2b/glue/customer_endpoints/customers/positive.robot
- tests/api/mp_b2b/glue/shopping_list_endpoints/shopping_list_items/positive.robot
> Mp b2b api refactoring new

- resources/common/common.robot
- resources/common/common_yves.robot
- resources/environments/environments_ui_b2b.json
- resources/environments/environments_ui_b2c.json
- resources/environments/environments_ui_mp_b2b.json
- resources/environments/environments_ui_mp_b2c.json
- resources/pages/yves/yves_product_configurator_page.robot
- resources/pages/yves/yves_product_details_page.robot
- resources/pages/yves/yves_shopping_cart_page.robot
- resources/steps/checkout_steps.robot
- resources/steps/configurable_product_steps.robot
- resources/steps/mp_orders_steps.robot
- resources/steps/order_history_steps.robot
- resources/steps/orders_management_steps.robot
- resources/steps/pdp_steps.robot
- resources/steps/shopping_carts_steps.robot
- resources/steps/wishlist_steps.robot
- tests/ui/e2e/e2e_b2b.robot
- tests/ui/e2e/e2e_b2c.robot
- tests/ui/e2e/e2e_mp_b2b.robot
- tests/ui/e2e/e2e_mp_b2c.robot
- product configuration from PDP, shopping cart, wishlist and shopping list
- an assertion that checkout is blocked for not configured product 
- Order placement and OMS process with configurable product
> Adding configurable product ui tests for 4 demoshops

- README.md
- install.sh
Added a `install.sh` script that will detect the python or python3 library automatically and run all the commands from the installation instructions automatically.
> Adding install.sh script to automate the installation steps

- tests/api/suite/glue/wishlist_endpoints/wishlist_items/positive.robot
> fix for postgress

- resources/environments/environments_api_b2c.json
- tests/api/b2c/glue/concrete_products_endpoints/concrete_product_availabilities/positive.robot
- tests/api/b2c/glue/configurable_bundle_endpoints/configurable_bundle/positive.robot
- tests/api/b2c/glue/wishlist_endpoints/wishlist_items/negative.robot
- tests/api/b2c/glue/wishlist_endpoints/wishlist_items/positive.robot
> B2c configurable product to wishlist

- resources/environments/environments_api_b2b.json
- tests/api/b2b/glue/shopping_list_endpoints/shopping_list_items/negative.robot
- tests/api/b2b/glue/shopping_list_endpoints/shopping_list_items/positive.robot
> B2b configurable product

- tests/api/b2c/glue/agent_endpoints/agent_access_tokens/positive.robot
- tests/api/b2c/glue/agent_endpoints/agent_customer_impersonation_access_tokens/negative.robot
- tests/api/b2c/glue/agent_endpoints/agent_customer_impersonation_access_tokens/positive.robot
- tests/api/b2c/glue/agent_endpoints/agent_customer_search/positive.robot
> B2c uncommented agen tests

- resources/environments/environments_api_mp_b2b.json
- tests/api/mp_b2b/glue/cart_endpoints/items/negative.robot
- tests/api/mp_b2b/glue/cart_endpoints/items/positive.robot
- tests/api/mp_b2b/glue/checkout_endpoints/checkout/negative.robot
- tests/api/mp_b2b/glue/checkout_endpoints/checkout/positive.robot
- tests/api/mp_b2b/glue/return_endpoints/returns/positive.robot
- tests/api/suite/glue/cart_endpoints/cart_items/positive.robot
> B2b mp fix self link, checkout, add configurable product tests

- resources/environments/environments_api_b2b.json
- resources/environments/environments_api_b2c.json
- resources/environments/environments_api_mp_b2c.json
- tests/api/b2b/glue/cart_endpoints/items/negative.robot
- tests/api/b2b/glue/cart_endpoints/items/positive.robot
- tests/api/b2b/glue/checkout_endpoints/checkout/positive.robot
- tests/api/b2c/glue/cart_endpoints/guest_cart_items/negative.robot
- tests/api/b2c/glue/cart_endpoints/guest_cart_items/positive.robot
- tests/api/b2c/glue/cart_endpoints/items/negative.robot
- tests/api/b2c/glue/cart_endpoints/items/positive.robot
- tests/api/b2c/glue/checkout_endpoints/checkout/positive.robot
- tests/api/mp_b2b/glue/cart_endpoints/items/negative.robot
- tests/api/mp_b2c/glue/cart_endpoints/items/negative.robot
- tests/api/mp_b2c/glue/cart_endpoints/items/positive.robot
- tests/api/mp_b2c/glue/checkout_endpoints/checkout/positive.robot
- tests/api/mp_b2c/glue/guest_carts/guest_cart_items/negative.robot
- tests/api/mp_b2c/glue/guest_carts/guest_cart_items/positive.robot
> All shops configurable product tests

- tests/api/b2b/glue/company_endpoints/company_users/negative.robot
> remove tag

- tests/api/suite/glue/cart_endpoints/cart_items/positive.robot
> fix for test

- tests/ui/regression/b2b.robot
- tests/ui/regression/b2c.robot
- tests/ui/regression/mp_b2b.robot
- tests/ui/regression/mp_b2c.robot
add Trigger oms 
- [x ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md
> add Trigger oms 

- resources/common/common.robot
- resources/pages/yves/yves_shopping_cart_page.robot
- resources/steps/order_comments_steps.robot
- resources/steps/orders_management_steps.robot
- tests/ui/e2e/b2b.robot
- tests/ui/e2e/mp_b2b.robot
- tests/ui/regression/b2b.robot
- tests/ui/regression/b2b_mp.robot
> improved oms error handling

- tests/ui/regression/b2b.robot
- tests/ui/regression/b2c.robot
- tests/ui/regression/mp_b2b.robot
- tests/ui/regression/mp_b2c.robot
additional fixes
- [ x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md
> OMS trigger fixes

- resources/steps/customer_account_steps.robot
- resources/steps/orders_management_steps.robot
- resources/steps/shopping_carts_steps.robot
- resources/steps/shopping_lists_steps.robot
- resources/steps/zed_discount_steps.robot
* improved OMS error handling
* increased Discount methods reliability 
* fixed overlapping issue of header elements
> Improved OMS errors handling

- resources/common/common.robot
add sleep to P&S method 
- [x ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md
> add sleep to P&S method 

- resources/common/common.robot
- tests/ui/regression/b2b.robot
- tests/ui/regression/b2c.robot
- tests/ui/regression/mp_b2b.robot
- tests/ui/regression/mp_b2c.robot
- tests/ui/smoke/b2b.robot
- tests/ui/smoke/b2c.robot
- tests/ui/smoke/mp_b2b.robot
- tests/ui/smoke/mp_b2c.robot
- add Trigger multistore p&s method 
- remove not used p&s from tests
- [ x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md
> add Trigger multistore p&s method and remove not used p&s from tests

- resources/environments/environments_api_b2b.json
- resources/environments/environments_api_b2c.json
- resources/environments/environments_api_mp_b2b.json
- resources/environments/environments_api_mp_b2c.json
- resources/environments/environments_api_suite.json
- tests/api/suite/bapi/warehouse_tokens/negative.robot
- tests/api/suite/bapi/warehouse_tokens/positive.robot
Merging tests for BAPI user token and warehouse token.
> Bapi warehouse tokens

- tests/api/suite/bapi/example_endpoints/example/positive.robot
skip example
- [x ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md
> skip example

- resources/steps/order_comments_steps.robot
- resources/steps/pdp_steps.robot
Add delays and fix keywords for add/edit/delete comments
> fix for several flaky tests

- resources/steps/request_for_quote_steps.robot
- tests/ui/e2e/mp_b2b.robot
Change OMS status to uppercase
> Change OMS status to Uppercase

- tests/api/b2b/glue/general_product_endpoints/product_reviews/negative.robot
- tests/api/b2c/glue/general_product_endpoints/product_reviews/negative.robot
- tests/api/mp_b2b/glue/general_product_endpoints/product_reviews/negative.robot
- tests/api/mp_b2c/glue/general_product_endpoints/product_reviews/negative.robot
- tests/api/suite/glue/general_product_endpoints/product_reviews/negative.robot
Fixed tests according to code fixes provided in https://spryker.atlassian.net/browse/CC-16486
> CC-16486 Fix robot test for product-reviews endpoint

- tests/api/b2c/glue/cart_endpoints/items/positive.robot
- tests/api/mp_b2c/glue/cart_endpoints/items/positive.robot
- tests/api/suite/glue/cart_endpoints/cart_items/positive.robot
Ticket: https://spryker.atlassian.net/browse/FRW-2313
> FRW-2313 Fixed failed test

- resources/common/common_api.robot
- tests/api/suite/glue/cart_endpoints/cart_items/positive.robot
> Clean cart keyword update

- tests/api/b2c/glue/cart_endpoints/guest_carts/positive.robot
> fix for b2c

- tests/api/mp_b2c/glue/cart_endpoints/guest_carts/positive.robot
> fix for mp_b2c

- tests/api/b2c/glue/cart_endpoints/guest_carts/positive.robot
- tests/api/mp_b2c/glue/cart_endpoints/guest_carts/positive.robot
> commented out 2 tests

- tests/api/b2c/glue/cart_endpoints/guest_carts/positive.robot
- tests/api/mp_b2c/glue/cart_endpoints/guest_carts/positive.robot
> commented out 1 tests for b2c and b2c_mp

- tests/api/suite/glue/cart_endpoints/guest_carts/positive.robot
> commented out test for suite

- tests/api/b2c/glue/cart_endpoints/guest_carts/positive.robot
- tests/api/mp_b2c/glue/cart_endpoints/guest_carts/positive.robot
> fix for guest cart

- tests/api/suite/glue/cart_endpoints/cart_items/positive.robot
> commented out test

- tests/api/b2c/glue/cart_endpoints/guest_carts/positive.robot
> fix for b2c test

- resources/common/common_api.robot
- tests/api/b2c/glue/cart_endpoints/guest_carts/positive.robot
- tests/api/mp_b2c/glue/cart_endpoints/guest_carts/positive.robot
- tests/api/suite/glue/cart_endpoints/cart_items/positive.robot
- tests/api/suite/glue/cart_endpoints/guest_carts/positive.robot
Update keyword: Cleanup all customer carts
Update several tests for suite-nonsplit, b2c, b2c_mp
PR verified on testing CI for suite-nonsplit: https://app.travis-ci.com/github/spryker/suite-nonsplit/builds/264620542
Verified for b2c_mp: https://github.com/spryker-shop/b2c-demo-marketplace/actions/runs/5600199198/jobs/10245534695
Verified for b2c: https://github.com/spryker-shop/b2c-demo-shop/actions/runs/5601720481
(for b2c_mp and b2c there are two failed tests related to review, task to update internal branch with fix already created)
TBD
> Update keyword: Cleanup all customer carts

- resources/common/common.robot
* added new keyword to click any web element with JS
> added new keyword to click any web element with JS

- tests/api/suite/bapi/dynamic_entity/negative.robot
Ticket: https://spryker.atlassian.net/browse/FRW-2369
> FRW-2369 Fixed error codes

- tests/api/b2b/glue/abstract_product_endpoints/abstract_product_prices/negative.robot
- tests/api/b2c/glue/abstract_product_endpoints/abstract_product_prices/negative.robot
- tests/api/mp_b2b/glue/abstract_product_endpoints/abstract_product_prices/negative.robot
- tests/api/mp_b2c/glue/abstract_product_endpoints/abstract_product_prices/negative.robot
- tests/api/suite/glue/abstract_product_endpoints/abstract_product_prices/negative.robot
remove price type for negative tests
> remove price type for negative tests

- tests/api/b2b/glue/abstract_product_endpoints/abstract_product_prices/positive.robot
> Api flaky test fix for one test

- tests/api/suite/bapi/dynamic_entity/negative.robot
Ticket: https://spryker.atlassian.net/browse/FRW-2376
PRs for check CI:
https://github.com/spryker/suite-nonsplit/pull/8065
https://github.com/spryker-shop/suite/pull/1336
> FRW-2376 adjusted expect error messages

- .github/workflows/b2b-demo-marketplace-smoke-ui.yml
- .github/workflows/b2b-demo-shop-smoke-ui.yml
- .github/workflows/b2c-demo-marketplace-regression-ui.yml
- .github/workflows/b2c-demo-marketplace-smoke-ui.yml
- .github/workflows/b2c-demo-shop-smoke-ui.yml
> CC-30088 Added demo-shops workflows for internal branch

- .github/workflows/b2b-demo-marketplace-regression-ui.yml
- .github/workflows/b2b-demo-shop-regression-ui.yml
- .github/workflows/b2c-demo-marketplace-regression-ui.yml
- .github/workflows/b2c-demo-shop-regression-ui.yml
> Added regression tests manual triggers.

- tests/api/suite/glue/general_product_endpoints/product_reviews/positive.robot
> remove-tag-for-test-where-bugs-are-fixed

- tests/api/b2b/glue/discount_endpoints/vouchers/positive.robot
- tests/api/b2b/glue/general_product_endpoints/product_reviews/positive.robot
- tests/api/b2b/glue/general_product_endpoints/product_tax_sets/negative.robot
- tests/api/b2b/glue/search_endpoints/catalog_search/positive.robot
- tests/api/b2b/glue/search_endpoints/catalog_search_suggestions/positive.robot
- tests/api/b2c/glue/general_product_endpoints/product_reviews/positive.robot
CC-16735
CC-16486
CC-25997
TBD
> remove-tags-for-tests-with -resolved-bugs

- tests/api/b2c/glue/general_product_endpoints/product_reviews/positive.robot
> remove tags for tests where issues have been resolved

- tests/api/mp_b2b/glue/abstract_product_endpoints/abstract_alternative_products/positive.robot
- tests/api/mp_b2b/glue/discount_endpoints/vouchers/negative.robot
- tests/api/mp_b2b/glue/discount_endpoints/vouchers/positive.robot
> remove tags

- tests/api/b2b/glue/discount_endpoints/vouchers/positive.robot
> add tags back, bug reproduced

- resources/common/common_api.robot
- resources/steps/shipment_type_steps.robot
- tests/api/suite/bapi/shipment_types/negative.robot
- tests/api/suite/bapi/shipment_types/positive.robot
> fix tests according to comments

- tests/api/b2b/sapi/utility_endpoints/stores/negative.robot
- tests/api/b2b/sapi/utility_endpoints/stores/positive.robot
- tests/api/b2c/sapi/utility_endpoints/stores/negative.robot
- tests/api/b2c/sapi/utility_endpoints/stores/positive.robot
- tests/api/mp_b2b/sapi/utility_endpoints/stores/negative.robot
- tests/api/mp_b2b/sapi/utility_endpoints/stores/positive.robot
- tests/api/mp_b2c/sapi/utility_endpoints/stores/negative.robot
- tests/api/mp_b2c/sapi/utility_endpoints/stores/positive.robot
Ticket: https://spryker.atlassian.net/browse/FRW-2308
> FRW-1610 Integrated Dynamic Store API coverage to demoshops

- resources/steps/shipment_type_steps.robot
> fixed request to work for both DB

- resources/steps/shipment_type_steps.robot
> Bapi shipment types, new condition for DB

- resources/environments/environments_api_suite.json
- resources/steps/push_notifications_steps.robot
- tests/api/suite/bapi/push_notification_endpoints/push_notification_subscriptions/negative.robot
- tests/api/suite/bapi/push_notification_endpoints/push_notification_subscriptions/positive.robot
Ticket: https://spryker.atlassian.net/browse/CC-29944
Suite: https://github.com/spryker/suite-nonsplit/pull/8132
> CC-29944 Added tests for PushNotificationSubscriptions

- resources/environments/environments_api_suite.json
> Bapi shipment types - fix env file after incorrect merging

- resources/steps/push_notifications_steps.robot
Ticket: https://spryker.atlassian.net/browse/CC-30653
> CC-31061 Fixed Postgres compatibility for push notification BAPI tests.

- resources/environments/environments_api_mp_b2b.json
- tests/api/mp_b2b/glue/abstract_product_endpoints/abstract_alternative_products/positive.robot
> fix tests and uncommented them

- tests/api/suite/bapi/shipment_types/positive.robot
Issues during releasing - https://github.com/spryker-shop/suite/actions/runs/5977932364/job/16221040928
> Skipping self-link tests due to failed release in suite repository.

- tests/api/suite/bapi/dynamic_entity/positive.robot
https://spryker.atlassian.net/browse/FRW-2435
> FRW-2435 Adjusted tests for Dynamic Exchange API

- resources/steps/request_for_quote_steps.robot
> fix for rfq

- tests/ui/e2e/b2b.robot
- tests/ui/e2e/b2c.robot
- tests/ui/regression/b2b.robot
- tests/ui/regression/b2c.robot
add timeout for catalog action tests
> catalog action tests fix

- resources/steps/request_for_quote_steps.robot
- tests/ui/e2e/b2b.robot
- tests/ui/regression/b2b.robot
> revert changes which is not helpful

- tests/api/suite/bapi/dynamic_entity/negative.robot
- tests/api/suite/bapi/dynamic_entity/positive.robot
> FRW-5841 Fixed robot tests

- tests/api/suite/bapi/shipment_types/positive.robot
This reverts commit dfd604485ae4373ed62355b8d14693425c95d94a.
> CC-30822 Un-skip shipment-types BAPI tests.

- tests/api/suite/bapi/dynamic_entity/negative.robot
https://spryker.atlassian.net/browse/FRW-6035
> FRW-6035 Fixed `FieldVisibleName` behaviour for Data Exchange API.

- tests/api/suite/bapi/dynamic_entity/negative.robot
- tests/api/suite/bapi/dynamic_entity/positive.robot
Ticket: https://spryker.atlassian.net/browse/FRW-6085
> FRW-6085 Fixed tests due to change structure response. 

- .github/workflows/b2b-demo-marketplace-regression-ui.yml
- .github/workflows/b2b-demo-marketplace-smoke-ui.yml
- .github/workflows/b2b-demo-shop-regression-ui.yml
- .github/workflows/b2c-demo-marketplace-regression-ui.yml
- .github/workflows/b2c-demo-marketplace-smoke-ui.yml
- .github/workflows/b2c-demo-shop-regression-ui.yml
- .github/workflows/b2c-demo-shop-smoke-ui.yml
Ticket: https://spryker.atlassian.net/browse/CC-31459
> CC-31459 Added spryker mail server host to all CI workflows.

- tests/api/b2b/glue/cart_endpoints/items/negative.robot
- tests/api/b2b/glue/shopping_list_endpoints/shopping_list_items/negative.robot
- tests/api/b2c/glue/cart_endpoints/guest_cart_items/negative.robot
- tests/api/b2c/glue/cart_endpoints/items/negative.robot
- tests/api/b2c/glue/wishlist_endpoints/wishlist_items/negative.robot
- tests/api/mp_b2b/glue/cart_endpoints/items/negative.robot
- tests/api/mp_b2b/glue/shopping_list_endpoints/shopping_list_items/negative.robot
- tests/api/mp_b2c/glue/cart_endpoints/items/negative.robot
- tests/api/mp_b2c/glue/guest_carts/guest_cart_items/negative.robot
- tests/api/mp_b2c/glue/wishlist_endpoints/wishlist_items/negative.robot
- tests/api/suite/glue/cart_endpoints/cart_items/negative.robot
- tests/api/suite/glue/guest_carts/guest_cart_items/negative.robot
- tests/api/suite/glue/shopping_list_endpoints/shopping_list_items/negative.robot
- tests/api/suite/glue/wishlist_endpoints/wishlist_items/negative.robot
Removed tests which are commented out by bug ticket: https://spryker.atlassian.net/browse/CC-25383
Tests are not relevant because availability validation happens during adding to the shopping cart and does not happen when we add the product to wishlist or shopping list.
Changed CC-25383 to CC-30918 for tests that are related to negative price cause it is another issue.
> Cc 25383 remove tests commented out with issue

- tests/api/suite/glue/cart_endpoints/cart_items/negative.robot
- tests/api/suite/glue/cart_endpoints/carts/positive.robot
Suite PR - https://github.com/spryker/suite-nonsplit/pull/8196
Core PR - https://github.com/spryker/spryker/pull/10459
Ticket - https://spryker.atlassian.net/browse/CC-31029
> CC-31029 Fixed exception for deactivated product in cart.

- resources/steps/warehouse_user_assigment_steps.robot
> fix keyword

- tests/api/suite/bapi/push_notification_endpoints/push_notification_provides/positive.robot
> fix 2 tests

- resources/environments/environments_api_suite.json
- resources/steps/warehouse_user_assigment_steps.robot
- tests/api/suite/bapi/push_notification_endpoints/push_notification_provides/negative.robot
- tests/api/suite/bapi/service_points/service_points/negative.robot
- tests/api/suite/bapi/warehouse_user_assignments/negative.robot
- tests/ui/e2e/b2c.robot
> fixes for comments after review

- resources/environments/environments_api_suite.json
- resources/steps/service_point_steps.robot
- resources/steps/warehouse_user_assigment_steps.robot
- tests/api/suite/bapi/push_notification_endpoints/push_notification_provides/negative.robot
- tests/api/suite/bapi/service_points/service_point_addresses/nagative.robot
- tests/api/suite/bapi/service_points/service_point_addresses/positive.robot
> Bapi service point address

- tests/api/mp_b2b/glue/cart_endpoints/carts/positive.robot
- tests/api/mp_b2b/glue/cart_endpoints/items/negative.robot
- Ticket: https://spryker.atlassian.net/browse/CC-31029
- Integration ticket: https://spryker.atlassian.net/browse/CC-31501
> CC-31029 Fixed exception for deactivated products in cart integration.

- Makefile
- resources/environments/environments_api_b2b.json
- resources/environments/environments_api_b2c.json
- resources/environments/environments_api_mp_b2b.json
- resources/environments/environments_api_mp_b2c.json
- resources/environments/environments_ui_b2b.json
- resources/environments/environments_ui_b2c.json
- resources/environments/environments_ui_mp_b2b.json
- resources/environments/environments_ui_mp_b2c.json
- resources/environments/environments_ui_suite.json
- resources/pages/zed/zed_data_exchange_api_configurator_page.robot
- resources/steps/dynamic_entity_steps.robot
- tests/api/b2b/bapi/dynamic_entity/negative.robot
- tests/api/b2b/bapi/dynamic_entity/positive.robot
- tests/api/b2c/bapi/dynamic_entity/negative.robot
- tests/api/b2c/bapi/dynamic_entity/positive.robot
- tests/api/mp_b2b/bapi/dynamic_entity/negative.robot
- tests/api/mp_b2b/bapi/dynamic_entity/positive.robot
- tests/api/mp_b2c/bapi/dynamic_entity/negative.robot
- tests/api/mp_b2c/bapi/dynamic_entity/positive.robot
- tests/ui/e2e/b2b.robot
- tests/ui/e2e/b2c.robot
- tests/ui/e2e/mp_b2b.robot
- tests/ui/e2e/mp_b2c.robot
* covered 2 authentication types for data exchange api
* new UI test for data exchange api
* integrated api tests for data exchange in 4 demoshops
> Data exchange api integration

- tests/api/suite/bapi/push_notification_endpoints/push_notification_provides/negative.robot
- Developer(s): @michbeck
- Ticket: https://spryker.atlassian.net/browse/CC-31549
- Release Group: https://release.spryker.com/release-groups/view/5057
Core PRs
- https://github.com/spryker/spryker/pull/10558
> CC-31549: Fixed delete invalid push notification provider status code

- resources/steps/warehouse_user_assigment_steps.robot
- tests/api/suite/bapi/fulfilment_app_e2e/positive.robot
> change keyword

- resources/steps/warehouse_user_assigment_steps.robot
- tests/api/suite/bapi/fulfilment_app_e2e/positive.robot
oms trigger
TBD
- [ x  ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md
> Fulfilment app e2e

- .github/workflows/b2c-demo-marketplace-smoke-ui.yml
> CC-31491 Added branch up-merge.

- resources/environments/environments_api_mp_b2c.json
> B2c mp integration dev

- resources/steps/orders_management_steps.robot
- tests/ui/e2e/b2b.robot
- tests/ui/e2e/b2c.robot
- added new OMS step processing in B2C E2E UI tests
- fixed order cancellation test due to new OMS logic
> update B2C UI tests due to new OMS logic (FA)

- resources/environments/environments_api_b2c.json
- resources/steps/warehouse_user_assigment_steps.robot
- tests/api/b2c/bapi/push_notification_endpoints/push_notification_providers/negative.robot
- tests/api/b2c/bapi/push_notification_endpoints/push_notification_providers/positive.robot
- tests/api/b2c/bapi/push_notification_endpoints/push_notification_subscriptions/negative.robot
- tests/api/b2c/bapi/push_notification_endpoints/push_notification_subscriptions/positive.robot
- tests/api/b2c/bapi/warehouse_tokens/negative.robot
- tests/api/b2c/bapi/warehouse_tokens/positive.robot
- tests/api/b2c/bapi/warehouse_user_assignments/negative.robot
- tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
> b2c integration for FA

- resources/environments/environments_ui_b2c.json
- tests/ui/e2e/b2c.robot
> Dev integration e2e fa

- tests/api/suite/bapi/fulfilment_app_e2e/positive.robot
Disabled FA E2E test for suite
> disable fa e2e for suite

- .github/workflows/b2b-demo-marketplace-regression-ui.yml
- .github/workflows/b2b-demo-shop-regression-ui.yml
- .github/workflows/b2c-demo-marketplace-regression-ui.yml
- .github/workflows/b2c-demo-shop-regression-ui.yml
Fixed tests run command to accept CLI commands
> fix github actions

- .github/workflows/b2b-demo-marketplace-regression-ui.yml
- .github/workflows/b2b-demo-shop-regression-ui.yml
- .github/workflows/b2c-demo-marketplace-regression-ui.yml
- .github/workflows/b2c-demo-shop-regression-ui.yml
> update yml files

- .github/workflows/b2c-demo-marketplace-regression-ui.yml
change regression to e2e folder
TBD
> fix b2c-mp yml for regression set

- tests/api/suite/bapi/service_points/service_types/negative.robot
Ticket: https://spryker.atlassian.net/browse/CC-31659
> CC-31659: Added missing content type header to Service Type tests

- tests/api/b2c/bapi/push_notification_endpoints/push_notification_providers/negative.robot
- tests/api/mp_b2c/bapi/push_notification_endpoints/push_notification_providers/negative.robot
[TBD](https://spryker.atlassian.net/browse/FRW-998)
> FRW-998 Fixed robot tests.

- tests/api/mp_b2b/glue/shopping_list_endpoints/shopping_list_items/positive.robot
> fix for flacky test

- resources/environments/environments_api_mp_b2c.json
- resources/steps/service_point_steps.robot
- tests/api/mp_b2c/bapi/service_points/service_point_addresses/negative.robot
- tests/api/mp_b2c/bapi/service_points/service_point_addresses/positive.robot
- tests/api/mp_b2c/bapi/service_points/service_points/negative.robot
- tests/api/mp_b2c/bapi/service_points/service_points/positive.robot
- tests/api/mp_b2c/bapi/service_points/service_types/negative.robot
- tests/api/mp_b2c/bapi/service_points/service_types/positive.robot
- tests/api/mp_b2c/bapi/service_points/services/negative.robot
- tests/api/mp_b2c/bapi/service_points/services/positive.robot
- tests/api/mp_b2c/bapi/shipment_types/negative.robot
- tests/api/mp_b2c/bapi/shipment_types/positive.robot
- tests/api/mp_b2c/glue/service_point_endpoints/service_point_addresses/negative.robot
- tests/api/mp_b2c/glue/service_point_endpoints/service_point_addresses/positive.robot
- tests/api/mp_b2c/glue/service_point_endpoints/service_points/negative.robot
- tests/api/mp_b2c/glue/service_point_endpoints/service_points/positive.robot
> B2c mp integration for click collect

- resources/pages/yves/yves_checkout_address_page.robot
- resources/steps/checkout_steps.robot
- resources/steps/dynamic_entity_steps.robot
- resources/steps/shopping_carts_steps.robot
- tests/api/b2b/bapi/dynamic_entity/positive.robot
- tests/api/b2c/bapi/dynamic_entity/positive.robot
- tests/api/mp_b2b/bapi/dynamic_entity/positive.robot
- tests/api/mp_b2c/bapi/dynamic_entity/positive.robot
- tests/api/suite/bapi/dynamic_entity/positive.robot
- tests/ui/e2e/mp_b2c.robot
- added click and collect UI E2E test for mp-b2c
- [x} I agree with the Code Contribution License Agreement in CONTRIBUTING.md
> click and collect ui test

- tests/ui/e2e/b2b.robot
- tests/ui/e2e/b2c.robot
- tests/ui/e2e/mp_b2b.robot
- tests/ui/e2e/mp_b2c.robot
Fix data exchange UI tests for CI env
> fix data exchange tests for CI env

- tests/ui/e2e/b2b.robot
- tests/ui/e2e/b2c.robot
- tests/ui/e2e/mp_b2b.robot
- tests/ui/e2e/mp_b2c.robot
fix admin user password change issue
> fix admin user password change issue

- resources/steps/checkout_steps.robot
- tests/ui/e2e/b2b.robot
- tests/ui/e2e/b2c.robot
- tests/ui/e2e/mp_b2b.robot
- tests/ui/e2e/mp_b2c.robot
Fixed checkout address selection logic for MP-B2C
> fix checkout pickup logic

- resources/common/common_ui.robot
- resources/pages/yves/yves_shopping_lists_page.robot
- resources/steps/catalog_steps.robot
- resources/steps/configurable_product_steps.robot
- resources/steps/mp_profile_steps.robot
- resources/steps/order_comments_steps.robot
- resources/steps/pdp_steps.robot
- resources/steps/shopping_carts_steps.robot
- resources/steps/shopping_lists_steps.robot
- resources/steps/zed_cms_page_steps.robot
- tests/ui/e2e/mp_b2b.robot
- tests/ui/e2e/mp_b2c.robot
> fix shopping list actions

- resources/common/common_mp.robot
- resources/common/common_yves.robot
- resources/common/common_zed.robot
- resources/steps/catalog_steps.robot
- resources/steps/checkout_steps.robot
- resources/steps/header_steps.robot
- resources/steps/mp_offers_steps.robot
- resources/steps/mp_products_steps.robot
- resources/steps/pdp_steps.robot
- resources/steps/zed_root_menus_steps.robot
- tests/ui/e2e/b2b.robot
- tests/ui/e2e/b2c.robot
- tests/ui/e2e/mp_b2b.robot
- tests/ui/e2e/mp_b2c.robot
* fixed teardown for data exchange tests
* fixed flaky merchant portal actions
> ui tests optimization

- resources/environments/environments_api_suite.json
- tests/api/suite/glue/general_product_endpoints/upselling_products/positive.robot
Ticket: https://spryker.atlassian.net/browse/CC-25880
> CC-25880 Changed product with upselling products

- resources/environments/environments_api_suite.json
- tests/api/b2c/bapi/warehouse_user_assignments/negative.robot
- tests/api/suite/glue/general_product_endpoints/upselling_products/positive.robot
Ticket: https://spryker.atlassian.net/browse/CC-25880
> fix upselling product review

- resources/environments/environments_api_suite.json
- tests/api/suite/bapi/push_notification_endpoints/push_notification_provides/positive.robot
- tests/api/suite/bapi/push_notification_endpoints/push_notification_subscriptions/negative.robot
- tests/api/suite/bapi/push_notification_endpoints/push_notification_subscriptions/positive.robot
- tests/api/suite/bapi/warehouse_user_assignments/negative.robot
- tests/api/suite/bapi/warehouse_user_assignments/positive.robot
https://spryker.atlassian.net/browse/CC-31859
> CC-31859: Restrict access to BAPI endpoints for merchant users

- resources/environments/environments_api_mp_b2c.json
- tests/api/b2c/bapi/warehouse_user_assignments/negative.robot
- tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
- tests/api/mp_b2c/bapi/warehouse_user_assignments/negative.robot
- tests/api/mp_b2c/bapi/warehouse_user_assignments/positive.robot
- tests/api/suite/bapi/fulfilment_app_e2e/positive.robot
add integration for access level for admin user and warehouse-user-assignment
> Dev warehouse access integration

- resources/environments/environments_api_mp_b2c.json
- tests/api/mp_b2c/bapi/push_notification_endpoints/push_notification_providers/positive.robot
- tests/api/mp_b2c/bapi/push_notification_endpoints/push_notification_subscriptions/negative.robot
- tests/api/mp_b2c/bapi/push_notification_endpoints/push_notification_subscriptions/positive.robot
https://spryker.atlassian.net/browse/CC-31859
> CC-31859: Restrict access to BAPI endpoints for merchant users for b2c-mp.

- tests/api/b2c/bapi/warehouse_user_assignments/negative.robot
- tests/api/b2c/bapi/warehouse_user_assignments/positive.robot
- tests/api/mp_b2c/bapi/warehouse_user_assignments/negative.robot
- tests/api/mp_b2c/bapi/warehouse_user_assignments/positive.robot
- tests/api/suite/bapi/warehouse_user_assignments/negative.robot
- tests/api/suite/bapi/warehouse_user_assignments/positive.robot
- Ticket: https://spryker.atlassian.net/browse/CC-31600
- Release Group: https://release.spryker.com/release-groups/view/5083
Reference all core PRs for auto-link back-references.
Core PRs
- https://github.com/spryker/suite-nonsplit/pull/8351
- https://github.com/spryker/spryker/pull/10580
> CC-31600: Fixed warehouse user assignment validation

- tests/api/suite/glue/concrete_products_endpoints/concrete_product_image_sets/positive.robot
Ticket: https://spryker.atlassian.net/browse/CC-25735
PR: https://github.com/spryker/suite-nonsplit/pull/8415
> CC-25735 Added images to product

- tests/api/suite/glue/guest_carts/guest_cart_items/negative.robot
- tests/api/suite/glue/shopping_list_endpoints/shopping_list_items/negative.robot
- tests/api/suite/glue/wishlist_endpoints/wishlist_items/negative.robot
- Developer(s): @romanhavrylko
- Ticket: https://spryker.atlassian.net/browse/CC-29261
- Release Group: https://release.spryker.com/release-groups/view/5126
- PR Overview: https://release.spryker.com/release/pull-request/10624
- merge: squash
Module                | Release Type         | Constraint Updates         |
:--------------------- | :------------------------ | :--------------------- |
ProductConfigurationShoppingListsRestApi  | patch                 |                       |
ProductConfigurationWishlistsRestApi  | patch                 |                       |
ProductConfigurationsRestApi  | patch                 |                       |
-----------------------------------------
Fixes
- Updated `shopping-lists.validation.yaml` so the prices in the product configuration in …
> CC-29261 Updated product configuration API validation.

- .github/workflows/b2b-demo-marketplace-regression-ui.yml
- .github/workflows/b2b-demo-shop-regression-ui.yml
- .github/workflows/b2c-demo-marketplace-regression-ui.yml
- .github/workflows/b2c-demo-shop-regression-ui.yml
Update upmerge command to merge latest release changes. Should be revert after UI run.
> change upmerge branch

- resources/common/common_zed.robot
- resources/steps/order_comments_steps.robot
- resources/steps/pdp_steps.robot
Fixed comment management UI steps
> fix-comment-management-ui-test

- resources/common/common_mp.robot
- resources/steps/mp_offers_steps.robot
- tests/ui/e2e/mp_b2c.robot
* refactored MP save action
* change grand total for `Fulfill_Order_from_Merchant_Portal` after bugfix: https://spryker.atlassian.net/browse/CC-31780
> marketplace steps refactoring

- .github/workflows/b2b-demo-marketplace-regression-ui.yml
- .github/workflows/b2b-demo-shop-regression-ui.yml
- .github/workflows/b2c-demo-marketplace-regression-ui.yml
- .github/workflows/b2c-demo-shop-regression-ui.yml
> revert changes

- resources/steps/customer_account_steps.robot
- resources/steps/customer_registration_steps.robot
- tests/ui/e2e/b2b.robot
- tests/ui/e2e/b2c.robot
- tests/ui/e2e/mp_b2b.robot
- tests/ui/e2e/mp_b2c.robot
* Optimized header actions: replaced `hover` step on `Go to URL`
> optimized header actions

- resources/steps/cms_steps.robot
- tests/api/suite/glue/content_endpoints/cms_pages/positive.robot
Ticket: https://spryker.atlassian.net/browse/CC-25472
> CC-25472 Fixed CMS page API tests.

- resources/steps/cms_steps.robot
- tests/api/suite/glue/content_endpoints/cms_pages/positive.robot
moving fix for CMS into DEV branch as well
> fix a tests

- tests/api/suite/bapi/dynamic_entity/negative.robot
- tests/api/suite/bapi/push_notification_endpoints/push_notification_provides/negative.robot
- tests/api/suite/bapi/service_points/service_point_addresses/negative.robot
- tests/api/suite/bapi/service_points/service_points/negative.robot
- tests/api/suite/bapi/service_points/service_types/negative.robot
- tests/api/suite/bapi/service_points/services/negative.robot
- tests/api/suite/bapi/shipment_types/negative.robot
- tests/api/suite/bapi/warehouse_user_assignments/negative.robot
Ticket: https://spryker.atlassian.net/browse/FRW-6285
> FRW-6285 Improved access token expiration

- .github/workflows/b2b-demo-marketplace-regression-ui-dev-robot.yml
- .github/workflows/b2b-demo-marketplace-regression-ui.yml
- .github/workflows/b2b-demo-shop-regression-ui-dev-robot.yml
- .github/workflows/b2c-demo-marketplace-regression-ui-dev-robot.yml
- .github/workflows/b2c-demo-marketplace-regression-ui.yml
- .github/workflows/b2c-demo-shop-regression-ui-dev-robot.yml
- .github/workflows/b2c-demo-shop-regression-ui.yml
- .github/workflows/suite-regression-ui-dev-robot.yml
- .github/workflows/suite-regression-ui.yml
> CC-32114 Added new CI files.

- .github/workflows/suite-regression-ui-dev-robot.yml
- .github/workflows/suite-regression-ui.yml
> CC-32114 Added fixes.

- resources/environments/environments_ui_suite.json
- resources/steps/orders_management_steps.robot
- tests/ui/e2e/b2b.robot
- tests/ui/e2e/b2c.robot
- tests/ui/e2e/mp_b2b.robot
- tests/ui/e2e/mp_b2c.robot
- tests/ui/e2e/suite.robot
* fix return management test: replaced browser page switch action on direct call
> fix return management test

- resources/environments/environments_ui_suite.json
- resources/steps/orders_management_steps.robot
- tests/ui/e2e/b2b.robot
- tests/ui/e2e/b2c.robot
- tests/ui/e2e/mp_b2b.robot
- tests/ui/e2e/mp_b2c.robot
- tests/ui/e2e/suite.robot
> merge master to dev

- resources/steps/orders_management_steps.robot
Fix print slip step for CI env
> Fix print slip step for CI env

- resources/steps/checkout_steps.robot
> Fix checkout address step

- .github/workflows/b2b-demo-marketplace-regression-ui-dev-robot.yml
- .github/workflows/b2b-demo-marketplace-regression-ui.yml
- .github/workflows/b2b-demo-shop-regression-ui-dev-robot.yml
- .github/workflows/b2b-demo-shop-regression-ui.yml
- .github/workflows/b2c-demo-marketplace-regression-ui-dev-robot.yml
- .github/workflows/b2c-demo-marketplace-regression-ui.yml
- .github/workflows/b2c-demo-shop-regression-ui-dev-robot.yml
- .github/workflows/b2c-demo-shop-regression-ui.yml
- .github/workflows/suite-regression-ui-dev-robot.yml
- .github/workflows/suite-regression-ui.yml
> CC-32114 Fixed deploy file and commands execution order.

- resources/steps/orders_management_steps.robot
- resources/steps/pdp_steps.robot
- tests/ui/e2e/mp_b2b.robot
- tests/ui/e2e/mp_b2c.robot
- tests/ui/e2e/suite.robot
> fix issues in CI env

- .github/workflows/b2b-demo-marketplace-regression-ui-dev-robot.yml
- resources/common/common_ui.robot
- tests/ui/e2e/b2b.robot
- tests/ui/e2e/b2c.robot
- tests/ui/e2e/mp_b2b.robot
- tests/ui/e2e/mp_b2c.robot
- tests/ui/e2e/suite.robot
> changed CI env build approach

- .github/workflows/b2b-demo-marketplace-regression-ui-dev-robot.yml
- .github/workflows/b2b-demo-shop-regression-ui-dev-robot.yml
- .github/workflows/b2c-demo-marketplace-regression-ui-dev-robot.yml
- .github/workflows/b2c-demo-shop-regression-ui-dev-robot.yml
- .github/workflows/suite-regression-ui-dev-robot.yml
- resources/common/common_ui.robot
- tests/ui/e2e/b2b.robot
- tests/ui/e2e/b2c.robot
- tests/ui/e2e/mp_b2b.robot
- tests/ui/e2e/mp_b2c.robot
- tests/ui/e2e/suite.robot
> Change CI env build approach

- tests/ui/e2e/suite.robot
update variable for fa e2e test
> Suite fa e2e

- resources/common/common_ui.robot
- resources/steps/pdp_steps.robot
- tests/ui/e2e/mp_b2c.robot
> fix P&S CI issue

- tests/ui/e2e/suite.robot
> fix suite UI tests for CI env

- resources/pages/yves/yves_shopping_carts_page.robot
- resources/steps/shopping_carts_steps.robot
update locators for table component
> update locators for table component

- .github/workflows/b2b-demo-marketplace-regression-ui.yml
- .github/workflows/b2b-demo-shop-regression-ui.yml
- .github/workflows/b2c-demo-marketplace-regression-ui.yml
- .github/workflows/b2c-demo-shop-regression-ui.yml
- .github/workflows/suite-regression-ui.yml
- resources/pages/yves/yves_wishlist_page.robot
- resources/steps/order_history_steps.robot
- resources/steps/wishlist_steps.robot
- resources/steps/zed_discount_steps.robot
- tests/ui/e2e/b2b.robot
- tests/ui/e2e/b2c.robot
- tests/ui/e2e/mp_b2b.robot
- tests/ui/e2e/mp_b2c.robot
- tests/ui/e2e/suite.robot
* changed P&C console command 
* added missing P&S steps
> Fix night ci

- tests/api/b2b/bapi/dynamic_entity/complex/negative.robot
- tests/api/b2b/bapi/dynamic_entity/complex/positive.robot
- tests/api/b2b/bapi/dynamic_entity/negative.robot
Tickets:
https://spryker.atlassian.net/browse/FRW-6331
https://spryker.atlassian.net/browse/FRW-6285
https://spryker.atlassian.net/browse/FRW-1162
https://spryker.atlassian.net/browse/FRW-1421
> FRW-1162 FRW-1421 FRW-6285 FRW-6331 Integrations. 

- tests/api/b2c/bapi/dynamic_entity/complex/negative.robot
- tests/api/b2c/bapi/dynamic_entity/complex/positive.robot
- tests/api/b2c/bapi/dynamic_entity/negative.robot
- tests/api/b2c/bapi/push_notification_endpoints/push_notification_providers/negative.robot
- tests/api/b2c/bapi/warehouse_user_assignments/negative.robot
Tickets:
https://spryker.atlassian.net/browse/FRW-6331
https://spryker.atlassian.net/browse/FRW-6285
https://spryker.atlassian.net/browse/FRW-1162
https://spryker.atlassian.net/browse/FRW-1421
> FRW-1162 FRW-1421 FRW-6285 FRW-6331 Integrations

- tests/api/mp_b2b/bapi/dynamic_entity/complex/negative.robot
- tests/api/mp_b2b/bapi/dynamic_entity/complex/positive.robot
- tests/api/mp_b2b/bapi/dynamic_entity/negative.robot
Tickets:
https://spryker.atlassian.net/browse/FRW-6331
https://spryker.atlassian.net/browse/FRW-6285
https://spryker.atlassian.net/browse/FRW-1162
https://spryker.atlassian.net/browse/FRW-1421
> FRW-1162 FRW-1421 FRW-6285 FRW-6331 Integrations robottests for b2b mp.

- tests/api/mp_b2c/bapi/dynamic_entity/complex/negative.robot
- tests/api/mp_b2c/bapi/dynamic_entity/complex/positive.robot
- tests/api/mp_b2c/bapi/dynamic_entity/negative.robot
- tests/api/mp_b2c/bapi/push_notification_endpoints/push_notification_providers/negative.robot
- tests/api/mp_b2c/bapi/service_points/service_point_addresses/negative.robot
- tests/api/mp_b2c/bapi/service_points/service_points/negative.robot
- tests/api/mp_b2c/bapi/service_points/service_types/negative.robot
- tests/api/mp_b2c/bapi/service_points/services/negative.robot
- tests/api/mp_b2c/bapi/shipment_types/negative.robot
- tests/api/mp_b2c/bapi/warehouse_user_assignments/negative.robot
Tickets:
https://spryker.atlassian.net/browse/FRW-6331
https://spryker.atlassian.net/browse/FRW-6285
https://spryker.atlassian.net/browse/FRW-1162
https://spryker.atlassian.net/browse/FRW-1421
> FRW-1162 FRW-1421 FRW-6285 FRW-6331 Integrations robottests for b2c mp.

- resources/pages/yves/yves_wishlist_page.robot
- resources/steps/wishlist_steps.robot
- tests/ui/e2e/suite.robot
> Fix night CI for suite

- tests/ui/e2e/suite.robot
Changed cancel order logic according to ACP changes
> Change cancel order logic according to ACP changes

- tests/ui/e2e/mp_b2c.robot
- tests/ui/e2e/suite.robot
> Merge 'master' to 'dev'

- tests/api/mp_b2c/bapi/push_notification_endpoints/push_notification_providers/positive.robot
- tests/api/suite/bapi/push_notification_endpoints/push_notification_provides/positive.robot
Ticket: https://spryker.atlassian.net/browse/CC-32438
> CC-32438 Fixed delete push notification provider test.

- resources/common/common.robot
- tests/ui/e2e/b2c.robot
- tests/ui/e2e/mp_b2c.robot
- tests/ui/e2e/suite.robot
* fixed new customer registration scenarios
> fix password validation

- resources/common/common.robot
- tests/ui/e2e/b2c.robot
- tests/ui/e2e/mp_b2c.robot
- tests/ui/e2e/suite.robot
* improved password complexity
> improved password complexity

- resources/environments/environments_api_suite.json
- Ticket: https://spryker.atlassian.net/browse/CC-25571
- Release Group: https://release.spryker.com/release-groups/view/5240
> CC-25571: Fixed not found standard label in demo data

- tests/ui/e2e/b2b.robot
- tests/ui/e2e/b2c.robot
- tests/ui/e2e/mp_b2b.robot
- tests/ui/e2e/mp_b2c.robot
- tests/ui/e2e/suite.robot
* removed merchant user email update action due to new logic
> remove merchant user email update

- .github/workflows/b2b-demo-marketplace-regression-api.yml
- .github/workflows/b2b-demo-shop-regression-api.yml
- .github/workflows/b2c-demo-marketplace-regression-api.yml
- .github/workflows/b2c-demo-shop-regression-api.yml
- .github/workflows/suite-regression-api.yml
- resources/common/common.robot
* added GA workflows for API nightly builds
* restored deleted Data_Exchage keywords
> Nigh CI for API regression testing

- .github/workflows/b2b-demo-marketplace-regression-api.yml
- .github/workflows/b2b-demo-shop-regression-api.yml
- .github/workflows/b2c-demo-marketplace-regression-api.yml
- .github/workflows/b2c-demo-shop-regression-api.yml
- .github/workflows/suite-regression-api.yml
- resources/common/common.robot
- tests/api/b2b/glue/abstract_product_endpoints/abstract_products/positive.robot
- tests/api/b2c/glue/abstract_product_endpoints/abstract_products/positive.robot
- tests/api/b2c/glue/concrete_products_endpoints/concrete_products/positive.robot
- tests/api/mp_b2b/glue/abstract_product_endpoints/abstract_products/positive.robot
- tests/api/mp_b2b/glue/concrete_products_endpoints/concrete_products/positive.robot
- tests/api/mp_b2b/glue/general_product_endpoints/upselling_products/positive.robot
- tests/api/mp_b2c/glue/abstract_product_endpoints/abstract_products/positive.robot
- tests/api/mp_b2c/glue/concrete_products_endpoints/concrete_products/positive.robot
- tests/api/mp_b2c/glue/general_product_endpoints/related_products/positive.robot
- tests/api/suite/bapi/service_points/service_points/positive.robot
- tests/api/suite/glue/abstract_product_endpoints/abstract_products/positive.robot
- tests/api/suite/glue/concrete_products_endpoints/concrete_products/positive.robot
- tests/api/suite/glue/general_product_endpoints/related_products/positive.robot
- tests/ui/e2e/b2c.robot
* Added product labels data sync before tests execution
> add product labels data sync

- tests/api/mp_b2b/glue/general_product_endpoints/upselling_products/positive.robot
- tests/api/mp_b2c/glue/general_product_endpoints/related_products/positive.robot
- tests/api/suite/glue/general_product_endpoints/related_products/positive.robot
fix token issue after cli command execution
> fix token issue after cli command execution

- resources/common/common.robot
- resources/common/common_api.robot
- resources/common/common_mp.robot
- resources/common/common_ui.robot
- resources/common/common_yves.robot
- resources/common/common_zed.robot
- resources/pages/yves/yves_catalog_page.robot
- resources/pages/yves/yves_company_users_page.robot
- resources/pages/yves/yves_delete_shopping_list_page.robot
- resources/pages/yves/yves_product_details_page.robot
- resources/pages/yves/yves_shopping_lists_page.robot
- resources/steps/catalog_steps.robot
- resources/steps/cms_steps.robot
- resources/steps/dynamic_entity_steps.robot
- resources/steps/header_steps.robot
- resources/steps/merchant_profile_steps.robot
- resources/steps/orders_management_steps.robot
- resources/steps/pdp_steps.robot
- resources/steps/request_for_quote_steps.robot
- resources/steps/service_point_steps.robot
- resources/steps/shipment_type_steps.robot
- resources/steps/warehouse_user_assigment_steps.robot
> Fix red ci

- .github/workflows/b2b-demo-marketplace-regression-api.yml
- .github/workflows/b2b-demo-shop-regression-api.yml
- .github/workflows/b2c-demo-marketplace-regression-api.yml
- .github/workflows/b2c-demo-shop-regression-api.yml
- .github/workflows/suite-regression-api.yml
- Makefile
* updated suite execution path after RF version 7.0 release
> update suite (-s) execution path after RF version 7.0 release

- resources/common/common.robot
- resources/steps/orders_management_steps.robot
- tests/ui/e2e/b2b.robot
- tests/ui/e2e/b2c.robot
- updated E2E UI tests for B2C/B2B according to the new 'cancel' action from ACP
> change order management logic for cancel action

- tests/ui/e2e/b2b.robot
> fix p&s for b2b

- .github/workflows/suite-regression-api-dms-on.yml
> change to acceptance yml

- .github/workflows/suite-regression-api-dms-on.yml
update dms yml, remove US region queue worker cli command
> remove US region queue worker cli command

- resources/common/common.robot
- resources/common/common_api.robot
- resources/environments/environments_api_suite.json
- tests/api/suite/dynamic_store/negative.robot
- tests/api/suite/dynamic_store/positive.robot
> Suite-nonsplit, revert changes for dms made by Nataliia P.

- tests/ui/e2e/suite.robot
changed title for agent role in BO
> changed title for agent role in BO

- .github/workflows/b2b-demo-shop-regression-ui.yml
- .github/workflows/b2c-demo-shop-regression-ui.yml
- resources/common/common_ui.robot
- resources/steps/pdp_steps.robot
- resources/steps/zed_cms_page_steps.robot
> Hotfix night ci

- .github/workflows/b2b-demo-marketplace-regression-ui.yml
- .github/workflows/b2c-demo-marketplace-regression-ui.yml
- .github/workflows/suite-regression-ui.yml
This loc is required till new version 18.0.1 for Browser library will be fix or change to 18.0.2
> loc 18.0.0 ver for Browser lib

- tests/ui/e2e/b2c.robot
- tests/ui/e2e/mp_b2c.robot
- tests/ui/e2e/suite.robot
fix passwords for suite-nonsplit UI tests
Register_during_checkout
New_Customer_Registration
> fix passwords new customer registration

- .github/suite-regression-ui-dms-on.yml
added new job for UI CI dms-on mode
added dms:on  into api yml as well
> new job for UI CI dms on

- .github/workflows/suite-regression-ui-dms-on.yml
> Updated MP url

- .github/workflows/b2b-demo-marketplace-regression-ui.yml
- .github/workflows/b2b-demo-shop-regression-ui.yml
- .github/workflows/b2c-demo-marketplace-regression-ui.yml
- .github/workflows/b2c-demo-shop-regression-ui.yml
- .github/workflows/suite-regression-ui.yml
* enable night ci for ui tests
> enable night ci for ui tests

- resources/common/common.robot
- resources/common/common_api.robot
- resources/common/common_ui.robot
- resources/pages/yves/yves_customer_account_page.robot
- resources/steps/customer_account_steps.robot
- tests/ui/e2e/suite.robot
Skip AT store related tests
fix Keyword with address
> skip several tests and fix one

- resources/steps/customer_account_steps.robot
- tests/api/suite/dynamic_store/negative.robot
- tests/api/suite/dynamic_store/positive.robot
Add condition for DMS
commented out example tests
> Fix piplines

- resources/pages/yves/yves_customer_account_page.robot
- resources/steps/customer_account_steps.robot
> fix for UI tests

- resources/common/common.robot
- tests/ui/e2e/b2b.robot
- tests/ui/e2e/b2c.robot
- tests/ui/e2e/mp_b2b.robot
- tests/ui/e2e/mp_b2c.robot
- tests/ui/e2e/suite.robot
Add fixes for failed DMS-ON related fix, add documentation for tests which has open issues.
> Add fixes for failed DMS-ON related fix, add documentation for tests which has open issues.

- tests/ui/e2e/suite.robot
Add documentation for DE tests with bug.
> add bug into documentation for DE

- .github/workflows/suite-regression-ui-dms-on.yml
- tests/api/suite/glue/configured_bundles_endpoints/guest_configured_bundles/positive.robot
change var glue_url to var current_url
> Suite tests dms on

- tests/api/b2c/glue/configured_bundles_endpoints/guest_configured_bundles/positive.robot
change harcoded glue variable to agile current url var
TBD
> fix config bundles for b2c

- tests/api/suite/bapi/dynamic_entity/complex/positive.robot
> FRW-7419 Adjusted test

- tests/ui/e2e/b2b.robot
- tests/ui/e2e/b2c.robot
- tests/ui/e2e/mp_b2b.robot
- tests/ui/e2e/mp_b2c.robot
Added documentation with bug links for DMS
> Demo shop tests refactoring

- tests/ui/e2e/b2b.robot
- tests/ui/e2e/b2c.robot
- tests/ui/e2e/mp_b2b.robot
- tests/ui/e2e/mp_b2c.robot
Skip failed tests with dms-off tag and skip teardown sections as well with keyword: Should Test Run.
> Skip failed tests with dms-off tag

- tests/ui/e2e/b2c.robot
- tests/ui/e2e/mp_b2c.robot
added link to bug ticket for failed availability test in b2c and b2c_mp
> added bug ticket link

- tests/ui/e2e/suite.robot
> added hot fix for flaky test

- .github/workflows/suite-regression-api-dev-branch.yml
- resources/steps/products_steps.robot
- tests/ui/e2e/b2b.robot
added additional p&s for availability test and new workflow which will be used to verify api changes in DEV robot branch
> added additional p&s for availability test and new workflow

- tests/api/suite/bapi/dynamic_entity/negative.robot
- tests/api/suite/bapi/dynamic_entity/positive.robot
https://spryker.atlassian.net/browse/FRW-7315
> FRW-6879 Test coverage

- resources/pages/yves/yves_shopping_cart_page.robot
- resources/steps/shopping_carts_steps.robot
- tests/api/suite/bapi/push_notification_endpoints/push_notification_provides/negative.robot
- tests/api/suite/bapi/service_points/service_point_addresses/negative.robot
- tests/api/suite/bapi/service_points/service_points/negative.robot
- tests/api/suite/bapi/shipment_types/negative.robot
- tests/api/suite/bapi/warehouse_tokens/negative.robot
- tests/api/suite/glue/checkout_endpoints/checkout/positive.robot
- tests/api/suite/glue/configurable_bundle_endpoints/configurable_bundle/negative.robot
- tests/api/suite/glue/product_offer_endpoints/product_offer_prices/negative.robot
- tests/api/suite/glue/product_offer_endpoints/product_offer_prices/positive.robot
- tests/api/suite/glue/product_offer_endpoints/product_offers/positive.robot
- tests/api/suite/glue/return_endpoints/returns/positive.robot
- tests/api/suite/glue/search_endpoints/catalog_search_suggestions/positive.robot
- tests/api/suite/glue/shopping_list_endpoints/shopping_lists/positive.robot
- tests/api/suite/glue/wishlist_endpoints/wishlists/negative.robot
- tests/ui/e2e/suite.robot
Uncommented and fix list of tests which were skipped because of bugs.
> uncommented list of tests

- .github/workflows/suite-regression-api-dev-branch.yml
> removed cron for DEV api job

- tests/api/suite/bapi/dynamic_entity/complex/positive.robot
Ticket: https://spryker.atlassian.net/browse/FRW-7291
> FRW-7291 Added test to check P&S works for child entities.

- .github/workflows/b2b-demo-marketplace-regression-ui-dynamic-multistore.yml
- .github/workflows/b2b-demo-shop-regression-ui-dynamic-multistore.yml
- .github/workflows/b2c-demo-marketplace-regression-ui-dynamic-multistore.yml
- .github/workflows/b2c-demo-shop-regression-ui-dynamic-multistore.yml
- .github/workflows/suite-regression-ui-dynamic-multistore.yml
* added date-time configurator host it project setup
> date-time configurator host it project setup

- tests/ui/e2e/mp_b2b.robot
> Added repeat for p&s

- resources/common/common.robot
- resources/common/common_mp.robot
- tests/ui/e2e/mp_b2b.robot
- tests/ui/e2e/suite.robot
> Change locator

- tests/ui/e2e/b2b.robot
- tests/ui/e2e/b2c.robot
- tests/ui/e2e/mp_b2b.robot
- tests/ui/e2e/mp_b2c.robot
- tests/ui/e2e/suite.robot
because of changed visual part of feature tests are commented out. New tests needs to be created
> commented out tests

- tests/api/b2b/bapi/dynamic_entity/complex/negative.robot
- tests/api/b2b/bapi/dynamic_entity/negative.robot
- tests/api/b2c/bapi/dynamic_entity/complex/negative.robot
- tests/api/b2c/bapi/dynamic_entity/negative.robot
- tests/api/mp_b2b/bapi/dynamic_entity/complex/negative.robot
- tests/api/mp_b2b/bapi/dynamic_entity/negative.robot
- tests/api/mp_b2c/bapi/dynamic_entity/complex/negative.robot
- tests/api/mp_b2c/bapi/dynamic_entity/negative.robot
- tests/api/suite/bapi/dynamic_entity/complex/negative.robot
> FRW-7296 Integration

- resources/pages/yves/yves_product_configurator_page.robot
- resources/steps/configurable_product_steps.robot
- resources/steps/zed_marketplace_steps.robot
- tests/ui/e2e/b2b.robot
- tests/ui/e2e/b2c.robot
- tests/ui/e2e/mp_b2b.robot
- tests/ui/e2e/mp_b2c.robot
- tests/ui/e2e/suite.robot
added new ui test for product configurator
> added new ui test for product configurator

- .github/workflows/b2b-demo-marketplace-regression-api-dynamic-multistore.yml
- .github/workflows/b2b-demo-marketplace-regression-api.yml
- .github/workflows/b2b-demo-marketplace-regression-ui-dynamic-multistore.yml
- .github/workflows/b2b-demo-marketplace-regression-ui.yml
- .github/workflows/b2b-demo-shop-regression-api-dynamic-multistore.yml
- .github/workflows/b2b-demo-shop-regression-api.yml
- .github/workflows/b2b-demo-shop-regression-ui-dynamic-multistore.yml
- .github/workflows/b2b-demo-shop-regression-ui.yml
- .github/workflows/b2c-demo-marketplace-regression-api-dynamic-multistore.yml
- .github/workflows/b2c-demo-marketplace-regression-api.yml
- .github/workflows/b2c-demo-marketplace-regression-ui-dynamic-multistore.yml
- .github/workflows/b2c-demo-marketplace-regression-ui.yml
- .github/workflows/b2c-demo-shop-regression-api-dynamic-multistore.yml
- .github/workflows/b2c-demo-shop-regression-api.yml
- .github/workflows/b2c-demo-shop-regression-ui-dynamic-multistore.yml
- .github/workflows/b2c-demo-shop-regression-ui.yml
- .github/workflows/suite-regression-api-dynamic-multistore.yml
- .github/workflows/suite-regression-api.yml
- .github/workflows/suite-regression-ui-dynamic-multistore.yml
- .github/workflows/suite-regression-ui.yml
add two folders for UI and API night ci
> add two folders for UI and API night ci

- resources/steps/zed_marketplace_steps.robot
> fixed issue with env var

- .github/workflows/suite-regression-ui.yml
- tests/ui/e2e/suite.robot
> test rerun in night ci

- .github/workflows/suite-regression-ui.yml
- tests/ui/e2e/suite.robot
rollback tests to the initial state
> rollback tests to the initial state

- .github/workflows/suite-regression-ui.yml
- tests/ui/e2e/suite.robot
> Enable rerun in night ci

- tests/ui/e2e/suite.robot
rollback UI tests for suite to the initial state
> rollback UI tests for suite to the initial state

- tests/ui/e2e/b2b.robot
- tests/ui/e2e/b2c.robot
- tests/ui/e2e/mp_b2c.robot
new feature has been added: if user click to already selected option it will unselect it.
> changed prices to new

- .github/workflows/b2b-demo-marketplace-regression-api-dynamic-multistore.yml
- .github/workflows/b2b-demo-marketplace-regression-api.yml
- .github/workflows/b2b-demo-marketplace-regression-ui-dev-robot.yml
- .github/workflows/b2b-demo-marketplace-regression-ui-dynamic-multistore.yml
- .github/workflows/b2b-demo-marketplace-regression-ui.yml
- .github/workflows/b2b-demo-shop-regression-api-dynamic-multistore.yml
- .github/workflows/b2b-demo-shop-regression-api.yml
- .github/workflows/b2b-demo-shop-regression-ui-dev-robot.yml
- .github/workflows/b2b-demo-shop-regression-ui-dynamic-multistore.yml
- .github/workflows/b2b-demo-shop-regression-ui.yml
- .github/workflows/b2c-demo-marketplace-regression-api-dynamic-multistore.yml
- .github/workflows/b2c-demo-marketplace-regression-api.yml
- .github/workflows/b2c-demo-marketplace-regression-ui-dev-robot.yml
- .github/workflows/b2c-demo-marketplace-regression-ui-dynamic-multistore.yml
- .github/workflows/b2c-demo-marketplace-regression-ui.yml
- .github/workflows/b2c-demo-shop-regression-api-dynamic-multistore.yml
- .github/workflows/b2c-demo-shop-regression-api.yml
- .github/workflows/b2c-demo-shop-regression-ui-dev-robot.yml
- .github/workflows/b2c-demo-shop-regression-ui-dynamic-multistore.yml
- .github/workflows/b2c-demo-shop-regression-ui.yml
changed internal to master for scheduled ci
> changed internal to master for scheduled ci

- resources/common/common.robot
- tests/api/suite/bapi/dynamic_entity/complex/positive.robot
- tests/api/suite/bapi/dynamic_entity/negative.robot
- tests/api/suite/bapi/dynamic_entity/positive.robot
https://spryker.atlassian.net/browse/FRW-6752
> FRW-6752 Adjusted robot tests

- tests/ui/e2e/b2c.robot
- tests/ui/e2e/mp_b2b.robot
fixed pricing for b2c and b2b_mp
> fixed pricing for b2c and b2b_mp

- resources/steps/products_steps.robot
> add fix to locator and test

- .github/workflows/b2b-demo-marketplace-regression-api-dynamic-multistore.yml
- .github/workflows/b2b-demo-marketplace-regression-api.yml
- .github/workflows/b2b-demo-marketplace-regression-ui-dynamic-multistore.yml
- .github/workflows/b2b-demo-marketplace-regression-ui.yml
- .github/workflows/b2b-demo-shop-regression-api-dynamic-multistore.yml
- .github/workflows/b2b-demo-shop-regression-api.yml
- .github/workflows/b2b-demo-shop-regression-ui-dynamic-multistore.yml
- .github/workflows/b2b-demo-shop-regression-ui.yml
- .github/workflows/b2c-demo-marketplace-regression-api-dynamic-multistore.yml
- .github/workflows/b2c-demo-marketplace-regression-api.yml
- .github/workflows/b2c-demo-marketplace-regression-ui-dynamic-multistore.yml
- .github/workflows/b2c-demo-marketplace-regression-ui.yml
- .github/workflows/b2c-demo-shop-regression-api-dynamic-multistore.yml
- .github/workflows/b2c-demo-shop-regression-api.yml
- .github/workflows/b2c-demo-shop-regression-ui-dynamic-multistore.yml
- .github/workflows/b2c-demo-shop-regression-ui.yml
- .github/workflows/suite-regression-api-dynamic-multistore.yml
- .github/workflows/suite-regression-api.yml
- .github/workflows/suite-regression-ui-dynamic-multistore.yml
- .github/workflows/suite-regression-ui.yml
Upgrade browser library version for UI tests
> upgrade Browser library version for UI tests

- resources/steps/zed_availability_steps.robot
- tests/ui/b2b/catalog/catalog.robot
> Adjusted keyword with new step

- resources/steps/pdp_steps.robot
- tests/ui/suite/customers/customer.robot
- fixed wishlist UI test in suite
> fixed wishlist UI test in suite

- resources/pages/yves/yves_shopping_cart_page.robot
Or condition for xpath to cover old version and new during transition period
> Add OR condition BC for 1 xpath

- resources/steps/header_steps.robot
- tests/ui/b2b/customers/customer.robot
added fix for env related xpath
> added fix for env related xpath

- resources/common/common_zed.robot
- tests/ui/b2b/customers/customer.robot
- tests/ui/mp_b2b/customers/customer.robot
- tests/ui/suite/customers/customer.robot
fix keyword save abstract product, fix var for shopping lists icon
> fixes for tests

- .github/workflows/b2b-demo-marketplace-regression-api-dynamic-multistore.yml
- .github/workflows/b2b-demo-marketplace-regression-api.yml
- .github/workflows/b2b-demo-marketplace-regression-ui-dynamic-multistore.yml
- .github/workflows/b2b-demo-marketplace-regression-ui.yml
- .github/workflows/b2b-demo-shop-regression-api-dynamic-multistore.yml
- .github/workflows/b2b-demo-shop-regression-api.yml
- .github/workflows/b2b-demo-shop-regression-ui-dynamic-multistore.yml
- .github/workflows/b2b-demo-shop-regression-ui.yml
- .github/workflows/b2c-demo-marketplace-regression-api-dynamic-multistore.yml
- .github/workflows/b2c-demo-marketplace-regression-api.yml
- .github/workflows/b2c-demo-marketplace-regression-ui-dynamic-multistore.yml
- .github/workflows/b2c-demo-marketplace-regression-ui.yml
- .github/workflows/b2c-demo-shop-regression-api-dynamic-multistore.yml
- .github/workflows/b2c-demo-shop-regression-api.yml
- .github/workflows/b2c-demo-shop-regression-ui-dynamic-multistore.yml
- .github/workflows/b2c-demo-shop-regression-ui.yml
- .github/workflows/suite-regression-api-dynamic-multistore.yml
- .github/workflows/suite-regression-api.yml
- .github/workflows/suite-regression-ui-dynamic-multistore.yml
- .github/workflows/suite-regression-ui.yml
added new time for api/api dms, ui/ui dms jobs
> added new time for api/api dms, ui/ui dms jobs

- tests/ui/suite/customers/customer.robot
suite nonsplit:
guest user should not see shopping list icon, should see cart icon
> revert changes, were broken by mistake

- resources/common/common_yves.robot
fixed issue with dynamic store
> Updated keyword with env var

- resources/common/common_yves.robot
- tests/ui/b2c/multistore/mustistore.robot
- tests/ui/mp_b2c/multistore/mustistore.robot
- tests/ui/suite/multistore/mustistore.robot
fixed mistake in env var and remove incorrect row from test
> fixed mistake in env var and remove incorrect row from test

- tests/api/suite/bapi/dynamic_entity/negative.robot
https://spryker.atlassian.net/browse/FRW-8560
> FRW-8567 Adjusted test.

- tests/api/b2b/bapi/dynamic_entity/negative.robot
- tests/api/b2b/bapi/dynamic_entity/positive.robot
- tests/api/b2c/bapi/dynamic_entity/negative.robot
- tests/api/b2c/bapi/dynamic_entity/positive.robot
- tests/api/mp_b2b/bapi/dynamic_entity/negative.robot
- tests/api/mp_b2b/bapi/dynamic_entity/positive.robot
- tests/api/mp_b2c/bapi/dynamic_entity/negative.robot
- tests/api/mp_b2c/bapi/dynamic_entity/positive.robot
> FRW Adjusted tests

- tests/ui/suite/catalog/catalog.robot
> fixed price

- resources/pages/yves/yves_shopping_cart_page.robot
Epic link: https://spryker.atlassian.net/browse/CC-16986
Task: https://spryker.atlassian.net/browse/CC-33480
> CC-16986: Update Cart Without Reload

- tests/ui/b2b/catalog/catalog.robot
- tests/ui/b2b/merchandising/merchandising.robot
- tests/ui/b2c/merchandising/merchandising.robot
- tests/ui/suite/merchandising/merchandising.robot
> Skipped test because of issue

- resources/common/common_zed.robot
- tests/ui/mp_b2b/marketplace/marketplace.robot
Test has been failed randomly with error:
"Actual product price is €100.00, expected €110.00" 
Seams that needs more time for p&s and I have added one more save.
> Added p&s and one step to save product

- tests/ui/mp_b2c/marketplace/marketplace.robot
> added additional P&S

- tests/api/mp_b2b/glue/merchant_endpoints/merchant_opening_hours/positive.robot
- tests/api/mp_b2c/glue/merchant_endpoints/merchant_opening_hours/positive.robot
- tests/api/suite/glue/merchant_endpoints/merchant_opening_hours/positive.robot
https://spryker.atlassian.net/browse/CC-33728
> CC-33728: Adjusted b2b-mp tests.

- resources/pages/zed/zed_store_page.robot
- resources/steps/zed_store_steps.robot
- tests/ui/suite/multistore/mustistore.robot
Ticket: https://spryker.atlassian.net/browse/FRW-7443
> FRW-7443 Adjusted store create UI test, added timezone.

- tests/ui/b2c/catalog/catalog.robot
> added new test

- resources/steps/configurable_product_steps.robot
- tests/ui/b2b/catalog/catalog.robot
- tests/ui/mp_b2b/catalog/catalog.robot
B2b configurable product tests
> B2B configurable product tests

- resources/pages/zed/zed_store_page.robot
> fixed xpath for dms test

- .github/workflows/b2b-demo-marketplace-regression-api-dynamic-multistore.yml
- .github/workflows/b2b-demo-marketplace-regression-api.yml
- .github/workflows/b2b-demo-marketplace-regression-ui-dynamic-multistore.yml
- .github/workflows/b2b-demo-marketplace-regression-ui.yml
- .github/workflows/b2b-demo-shop-regression-api-dynamic-multistore.yml
- .github/workflows/b2b-demo-shop-regression-api.yml
- .github/workflows/b2b-demo-shop-regression-ui-dynamic-multistore.yml
- .github/workflows/b2b-demo-shop-regression-ui.yml
- .github/workflows/b2c-demo-marketplace-regression-api-dynamic-multistore.yml
- .github/workflows/b2c-demo-marketplace-regression-api.yml
- .github/workflows/b2c-demo-marketplace-regression-ui-dynamic-multistore.yml
- .github/workflows/b2c-demo-marketplace-regression-ui.yml
- .github/workflows/b2c-demo-shop-regression-api-dynamic-multistore.yml
- .github/workflows/b2c-demo-shop-regression-api.yml
- .github/workflows/b2c-demo-shop-regression-ui-dynamic-multistore.yml
- .github/workflows/b2c-demo-shop-regression-ui.yml
- .github/workflows/suite-regression-api-dynamic-multistore.yml
- .github/workflows/suite-regression-api.yml
- .github/workflows/suite-regression-ui-dynamic-multistore.yml
- .github/workflows/suite-regression-ui.yml
changed if always to if failure for upload artefacts
> changed if always to if failure for upload artefacts

- resources/steps/shopping_carts_steps.robot
- tests/ui/mp_b2b/marketplace/marketplace.robot
- tests/ui/mp_b2b/multistore/mustistore.robot
- tests/ui/mp_b2c/marketplace/marketplace.robot
- tests/ui/mp_b2c/multistore/mustistore.robot
- tests/ui/suite/marketplace/marketplace.robot
- tests/ui/suite/multistore/mustistore.robot
* added extra p&s trigger
* change logic in merchant_product test
> fix flaky test

- tests/ui/b2b/checkout/checkout.robot
- tests/ui/b2c/checkout/checkout.robot
- tests/ui/mp_b2b/checkout/checkout.robot
- tests/ui/mp_b2c/checkout/checkout.robot
- tests/ui/suite/checkout/checkout.robot
updated configurable product tests
> updated configurable product tests

- tests/ui/b2b/multistore/mustistore.robot
- tests/ui/b2c/multistore/mustistore.robot
- tests/ui/suite/multistore/mustistore.robot
> stabilization

- resources/environments/environments_ui_suite.json
- tests/ui/suite/marketplace/marketplace.robot
- Ticket: https://spryker.atlassian.net/browse/FRW-8932
> FRW-8932 Fixed issue with Marketplace homepage.

- resources/environments/environments_ui_mp_b2b.json
- resources/environments/environments_ui_mp_b2c.json
- tests/ui/mp_b2b/marketplace/marketplace.robot
- tests/ui/mp_b2c/marketplace/marketplace.robot
https://spryker.atlassian.net/browse/FRW-8932
> FRW-8932 Added robot tests for Merchant Portal homepage bug.

- .github/workflows/suite-regression-api-dynamic-multistore.yml
- .github/workflows/suite-regression-api.yml
- .github/workflows/suite-regression-ui-dynamic-multistore.yml
- .github/workflows/suite-regression-ui.yml
- resources/environments/environments_api_suite.json
- resources/environments/environments_ui_suite.json
- disabled scheduled workflows for DMS ON in suite
- changed suite env variables
- updated nighCI configuration
> enable dms on in suite by default

- resources/pages/mp/mp_product_drawer.robot
- resources/steps/mp_products_steps.robot
- tests/ui/mp_b2b/catalog/catalog.robot
- tests/ui/mp_b2b/marketplace/marketplace.robot
- tests/ui/mp_b2b/multistore/mustistore.robot
- tests/ui/mp_b2c/catalog/catalog.robot
- tests/ui/mp_b2c/checkout/checkout.robot
- tests/ui/mp_b2c/marketplace/marketplace.robot
- tests/ui/mp_b2c/multistore/mustistore.robot
- tests/ui/suite/catalog/catalog.robot
- tests/ui/suite/checkout/checkout.robot
- tests/ui/suite/marketplace/marketplace.robot
- tests/ui/suite/merchandising/merchandising.robot
- tests/ui/suite/multistore/mustistore.robot
- Added locales support in Merchant Product creation flow
> Enable locales in Merchant Product creation

- resources/common/common_yves.robot
- tests/ui/b2c/customers/customer.robot
- tests/ui/mp_b2c/customers/customer.robot
- tests/ui/suite/customers/customer.robot
Ticket:  https://spryker.atlassian.net/browse/FRW-8883
Improvements
- Added a test for customer login with an unconfirmed email.
- Added a keyword to log in a customer into Yves and expect an error.
> FRW-8883 Fixed customer login so that email confirmation is checked and errors are correctly reported.

- .github/workflows/debug-b2b-mp-postgres-ui-dms-off.yml
- resources/common/common_mp.robot
- resources/steps/checkout_steps.robot
- resources/steps/mp_products_steps.robot
- resources/steps/pdp_steps.robot
- resources/steps/shopping_carts_steps.robot
- tests/ui/mp_b2b/catalog/catalog.robot
> Fix CI B2B-MP postgres

- resources/common/common.robot
- resources/steps/configurable_product_steps.robot
- resources/steps/pdp_steps.robot
- resources/steps/shopping_carts_steps.robot
- tests/ui/mp_b2b/catalog/catalog.robot
- removed extra step with cart cration
- removed extra sleeps
> Fix B2B-MP CI

- resources/common/common.robot
- resources/steps/customer_account_steps.robot
- resources/steps/header_steps.robot
- tests/ui/b2b/catalog/catalog.robot
- tests/ui/b2b/checkout/checkout.robot
- tests/ui/b2b/merchandising/merchandising.robot
- tests/ui/b2c/merchandising/merchandising.robot
- tests/ui/mp_b2b/catalog/catalog.robot
- tests/ui/mp_b2b/checkout/checkout.robot
- tests/ui/mp_b2b/merchandising/merchandising.robot
- tests/ui/mp_b2c/merchandising/merchandising.robot
- tests/ui/suite/catalog/catalog.robot
- tests/ui/suite/checkout/checkout.robot
- tests/ui/suite/customers/customer.robot
- tests/ui/suite/merchandising/merchandising.robot
- tests/ui/suite/sales/sales.robot
- changed checkout step to use existing address instead of creating a new one
> fix checkout address issue

- resources/steps/zed_users_steps.robot
- tests/ui/b2b/users/users.robot
- tests/ui/b2c/users/users.robot
- tests/ui/mp_b2b/users/users.robot
- tests/ui/mp_b2c/users/users.robot
> FRW-9170 Back office user management

- tests/api/suite/bapi/dynamic_entity/complex/negative.robot
https://spryker.atlassian.net/browse/FRW-9407
BC-check https://github.com/spryker/suite-nonsplit/pull/9189
> FRW-9407 Fixed robot tests for missing DataExchangeAPI complex request fields.

- tests/api/b2b/glue/customer_endpoints/customer_password/negative.robot
- tests/api/b2b/glue/customer_endpoints/customers/negative.robot
- tests/api/b2c/glue/customer_endpoints/customer_password/negative.robot
- tests/api/mp_b2b/glue/customer_endpoints/customer_password/negative.robot
- tests/api/mp_b2b/glue/customer_endpoints/customers/negative.robot
- tests/api/mp_b2c/glue/customer_endpoints/customer_password/negative.robot
- tests/api/suite/glue/customer_endpoints/customer_password/negative.robot
- tests/api/suite/glue/customer_endpoints/customers/negative.robot
Ticket: https://spryker.atlassian.net/browse/FRW-9641
> FRW-9641 Adjusted tests

- tests/ui/suite/catalog/catalog.robot
- tests/ui/suite/checkout/checkout.robot
- tests/ui/suite/marketplace/marketplace.robot
- tests/ui/suite/merchandising/merchandising.robot
- tests/ui/suite/sales/sales.robot
Added new OMS transition to match new logic
> CC-34502 Order amendment grace period

- resources/common/common.robot
Ticket: https://spryker.atlassian.net/browse/SSP-1
This is a mandatory step to make sure you are aware of the license agreement and agree to it. `HASH_OF_COMMIT_YOU_ARE_BASING_YOUR_BRANCH_FROM_MASTER_BRANCH` is a hash of the commit you are basing your branch from the master branch. You can take it from commits list of master branch before you submit …
> SSP-1: refactor order item status change keyword

- tests/api/b2b/glue/customer_endpoints/customer_password/negative.robot
- tests/api/b2b/glue/customer_endpoints/customers/negative.robot
- tests/api/b2c/glue/customer_endpoints/customer_password/negative.robot
- tests/api/mp_b2b/glue/customer_endpoints/customer_password/negative.robot
- tests/api/mp_b2b/glue/customer_endpoints/customers/negative.robot
- tests/api/mp_b2c/glue/customer_endpoints/customer_password/negative.robot
- tests/api/suite/glue/customer_endpoints/customer_password/negative.robot
- tests/api/suite/glue/customer_endpoints/customers/negative.robot
Ticket: https://spryker.atlassian.net/browse/FRW-10005
> FRW-10005 Removed wrong tests

- .github/workflows/dev-mp-b2b-ui-dms-on-parallel-testlevel.yml
> Create test CI

- .github/workflows/dev-b2b-ui-dms-on-parallel.yml
- .github/workflows/dev-b2c-ui-dms-on-parallel.yml
- .github/workflows/dev-mp-b2b-ui-dms-on-parallel-testlevel.yml
- .github/workflows/dev-mp-b2b-ui-dms-on-parallel.yml
- .github/workflows/dev-mp-b2c-ui-dms-on-parallel.yml
- .github/workflows/dev-suite-ui-dms-on-one-process.yml
- .github/workflows/dev-suite-ui-dms-on-parallel.yml
> FRW-9914 update test CI

- tests/ui/b2b/checkout/checkout.robot
- Disabled flaky B2B UI test until refactored
This is a mandatory step to make sure you are aware of the license agreement and agree to it. `HASH_OF_COMMIT_YOU_ARE_BASING_YOUR_BRANCH_FROM_MASTER_BRANCH` is a hash of the commit you are basing your branch from the master branch. You can take it from commits list of master branch before you submit a PR.
> disable flaky B2B UI test

- resources/common/common_api.robot
- resources/environments/environments_api_suite.json
- resources/steps/api_service_point_steps.robot
- resources/steps/checkout_steps.robot
- tests/api/suite/bapi/dynamic_entity/complex/negative.robot
- tests/api/suite/bapi/service_points/service_types/positive.robot
- tests/api/suite/glue/search_endpoints/catalog_search/positive.robot
- tests/ui/mp_b2c/checkout/checkout.robot
- tests/ui/suite/checkout/checkout.robot
- tests/ui/suite/merchandising/merchandising.robot
- Ticket: https://spryker.atlassian.net/browse/SSP-3
Reference all core PRs for auto-link back-references.
Core PRs
- https://github.com/spryker/spryker/pull/11402
- https://github.com/spryker/spryker-shop/pull/2619
{Relevant changes for project level go here. Those will be copied to the release log for suite if necessary.}
> SSP-3 adjust API tests

- tests/ui/suite/catalog/catalog.robot
- tests/ui/suite/marketplace/marketplace.robot
- tests/ui/suite/sales/sales.robot
- https://spryker.atlassian.net/browse/CC-35506
Added 'skip grace period' for suite environment.
> CC-35506: Cancel amendable orders

- tests/api/suite/bapi/dynamic_entity/positive.robot
Ticket: https://spryker.atlassian.net/browse/FRW-9822
> FRW-9822 Adjusted country tests.

- tests/api/b2b/glue/access_token_endpoints/refresh_tokens/negative.robot
- tests/api/b2b/glue/access_token_endpoints/refresh_tokens/positive.robot
- tests/api/b2c/glue/access_token_endpoints/refresh_tokens/negative.robot
- tests/api/b2c/glue/access_token_endpoints/refresh_tokens/positive.robot
- tests/api/mp_b2b/glue/access_token_endpoints/refresh_tokens/negative.robot
- tests/api/mp_b2b/glue/access_token_endpoints/refresh_tokens/positive.robot
- tests/api/mp_b2c/glue/access_token_endpoints/refresh_tokens/negative.robot
- tests/api/mp_b2c/glue/access_token_endpoints/refresh_tokens/positive.robot
- tests/api/suite/glue/access_token_endpoints/refresh_tokens/negative.robot
- tests/api/suite/glue/access_token_endpoints/refresh_tokens/positive.robot
Tickets: 
- https://spryker.atlassian.net/browse/SUPESC-939
- https://spryker.atlassian.net/browse/FRW-10160
This is a mandatory step to make sure you are aware of the license agreement and agree to it. `HASH_OF_COMMIT_YOU_ARE_BASING_YOUR_BRANCH_FROM_MASTER_BRANCH` is a hash of the commit you are basing your branch from the master branch. You can …
> SUPESC-939 disable delete token tests

- resources/environments/environments_api_suite.json
- resources/steps/api_service_point_steps.robot
- tests/api/suite/bapi/dynamic_entity/complex/positive.robot
- tests/api/suite/bapi/service_points/service_types/positive.robot
- tests/api/suite/glue/category_endpoints/category_trees/positive.robot
- tests/api/suite/glue/search_endpoints/catalog_search/positive.robot
- tests/api/suite/glue/service_points_endpoints/service_points/positive.robot
- tests/ui/suite/customers/customer.robot
- tests/ui/suite/marketplace/marketplace.robot
https://spryker.atlassian.net/browse/SSP-776
> SSP-776 fixed robot tests.

- tests/ui/b2b/company/company.robot
- tests/ui/mp_b2b/company/company.robot
- tests/ui/suite/company/company.robot
> Fix failing CI

- tests/api/suite/glue/quote_requests_endpoint/quote_requests/negative.robot
> CC-35711: [Fixathon] RfQ API Improvements (GA).

- resources/common/common_zed.robot
> CC-35706 adjusted search input search BO

- resources/common/common_api.robot
> disable API retries

- resources/pages/mp/mp_account_page.robot
Fix is needed for https://github.com/spryker-shop/b2b-demo-marketplace/actions/runs/16274033556/job/45948479547?pr=666
> Fixed the selector for MP

- resources/common/common_zed.robot
https://spryker.atlassian.net/browse/SSP-955
> SSP-995 Fixed robot tests.

- resources/pages/yves/yves_catalog_page.robot
> SSP-1161: fix robot tests

- resources/steps/checkout_steps.robot
> Fix checkout step locator

- tests/api/b2b/glue/search_endpoints/catalog_search_suggestions/positive.robot
- tests/api/mp_b2b/glue/search_endpoints/catalog_search_suggestions/positive.robot
- tests/api/mp_b2c/glue/search_endpoints/catalog_search_suggestions/positive.robot
> Change price assertion logic

- tests/parallel_ui/suite/customers/customer.robot
- tests/parallel_ui/suite/sales/sales.robot
> skip noncritical tests in suite
